'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const M=require('../bennyshub/apps/games/NARBEPICKLEBALL/js/model.js');
function live(options={}){const s=M.create(options);s.phase='ready';s.rallyClosed=false;return s;}
function until(s,predicate,slow=true){for(let i=0;i<5000&&!predicate(s);i++)M.update(s,.01,slow);assert.ok(predicate(s),'simulation reached expected phase');}
test('Singles: a server fault changes service without awarding a receiver point',()=>{const s=live();assert.ok(M.miss(s));assert.deepEqual(s.score,[0,0]);assert.equal(s.server,1);assert.equal(s.lastEvent,'sideout');assert.equal(M.miss(s),false);assert.equal(M.point(s,1,'Duplicate'),false);});
test('Only the serving side scores, on either side of the net',()=>{for(const server of [0,1]){const s=live();s.server=server;M.point(s,server,'Winner');assert.equal(s.score[server],1);assert.equal(s.score[1-server],0);assert.equal(s.server,server);}});
test('Matches go to eleven with a two-point margin, including deuce',()=>{const s=live();s.score=[10,10];M.point(s,0,'Winner');assert.equal(s.phase,'point');assert.deepEqual(s.score,[11,10]);M.prepareServe(s);M.beginServe(s);M.point(s,0,'Winner');assert.equal(s.phase,'over');assert.equal(s.winner,0);assert.deepEqual(s.score,[12,10]);});
test('Every resolved rally waits for an explicit next serve',()=>{const s=live();M.miss(s);until(s,x=>x.phase==='serve');for(let i=0;i<1000;i++)M.update(s,.05);assert.equal(s.phase,'serve');assert.equal(s.flight,null);assert.deepEqual(s.score,[0,0]);assert.ok(M.beginServe(s));assert.equal(M.beginServe(s),false);});
test('Even/odd serves use the correct baseline side and opposite service box',()=>{for(const server of [0,1])for(const points of [0,1,2,9]){const s=M.create();s.server=server;s.score[server]=points;M.prepareServe(s);const serving=server===0?s.player:s.cpu;assert.ok(Math.abs(serving.z)>6.7);assert.equal(Math.sign(serving.x),(points%2===0?1:-1)*(server===0?1:-1));assert.ok(M.beginServe(s));const f=s.flight;assert.equal(Math.sign(f.to.x),-Math.sign(f.from.x));assert.ok(Math.abs(f.to.z)>2.13&&Math.abs(f.to.z)<6.7);assert.ok(Math.abs(f.to.x)<3.05);}});
test('Serve and return each bounce before they can be returned',()=>{const s=M.create({mode:'rally'});M.prepareServe(s);M.beginServe(s);assert.equal(M.autoReturn(s),false);let cpuBounce=false,playerBounce=false;for(let i=0;i<2000&&s.phase!=='ready';i++){if(s.flight?.direction==='out'&&s.flight.bounced)cpuBounce=true;if(s.flight?.direction==='in'&&s.flight.bounced)playerBounce=true;M.update(s,.01);}assert.ok(cpuBounce&&playerBounce);assert.equal(s.phase,'ready');});
test('An already returned ball cannot be scored as a player miss',()=>{const s=live();assert.ok(M.autoReturn(s));const event=s.event;assert.equal(s.flight.direction,'out');assert.equal(M.miss(s),false);assert.equal(M.autoReturn(s),false);assert.deepEqual(s.score,[0,0]);assert.equal(s.event,event);assert.equal(s.rally,1);});
test('Forehand and backhand both return automatically; better contact is stronger',()=>{for(const side of [-1,1]){const clean=live(),stretch=live();clean.ball.x=side*.4;stretch.ball.x=side*1.05;assert.ok(M.autoReturn(clean));assert.ok(M.autoReturn(stretch));assert.equal(clean.lastHitSide,side);assert.ok(clean.contactQuality>stretch.contactQuality);assert.ok(clean.power>stretch.power);assert.ok(clean.flight.duration<stretch.flight.duration);assert.equal(stretch.lastPlay,'dive');}const missed=live();missed.ball.x=1.3;assert.equal(M.autoReturn(missed),false);});
test('Manual and one-switch controls do not automatically move sideways',()=>{for(const controlMode of ['manual','one','assisted']){const s=M.create({controlMode});s.server=1;M.prepareServe(s);s.player.x=-2.7;M.beginServe(s);for(let i=0;i<100;i++)M.update(s,.01);if(controlMode==='assisted')assert.ok(s.player.x>0);else assert.equal(s.player.x,-2.7);}});
test('Held movement is continuous, bounded, and stops at an edge without reversing itself',()=>{const s=live();s.moveDir=-1;M.movePlayer(s,-1,.5,1.8);assert.equal(s.player.x,-.9);M.movePlayer(s,1,.25,1.8);assert.equal(s.player.x,-.45);M.movePlayer(s,-1,10,1.8);assert.equal(s.player.x,-2.7);assert.equal(s.moveDir,-1);});
test('Full speed removes approach slowdown while slow play preserves it',()=>{const times=[];for(const slow of [false,true]){const s=M.create();s.server=1;M.prepareServe(s);M.beginServe(s);let time=0;while(s.phase==='flight'){M.update(s,.01,slow);time+=.01;}times.push(time);}assert.ok(times[0]<1.7);assert.ok(times[1]>times[0]+1);});
test('The robot automatically covers multiple depths; every return stays continuous',()=>{const depths=new Set();for(let i=0;i<6;i++){const s=live({mode:'rally'});s.rally=i;M.hit(s,0,'drive',true,.4);until(s,x=>x.flight?.direction==='in');depths.add(s.flight.contact.z);let previous={...s.ball},bounce=false,maxHop=0;while(s.phase==='flight'){M.update(s,.01);maxHop=Math.max(maxHop,Math.hypot(s.ball.x-previous.x,s.ball.y-previous.y,s.ball.z-previous.z));previous={...s.ball};if(s.flight?.bounced)bounce=true;}assert.ok(bounce);assert.ok(maxHop<.15);assert.ok(Math.abs(s.player.z-(s.ball.z+M.zoneDepth(s.ball.y)))<.1);}assert.ok(depths.size>=3);});
test('Automatic returns clear the net and stay within court bounds',()=>{for(const shot of ['drive','dink','lob'])for(const z of [1.75,3.7,4.9]){const s=live();s.ball.z=z;M.hit(s,2.6,shot,true,.1);const f=s.flight,u=-f.from.z/(f.to.z-f.from.z),p=M.sampleFlight(f,u*f.bounceAt);assert.ok(p.y-M.BALL_RADIUS>1.08);assert.ok(Math.abs(f.to.x)<=3.05&&Math.abs(f.to.z)<=6.7);}});
test('No-fail practice does not award opponent points',()=>{const s=live({mode:'rally'});M.miss(s);assert.deepEqual(s.score,[0,0]);assert.equal(s.winner,null);});
test('Saved continuous flights resume identically',()=>{const s=M.create({controlMode:'one'});s.server=1;M.prepareServe(s);M.beginServe(s);for(let i=0;i<190;i++)M.update(s,.01);const restored=JSON.parse(JSON.stringify(s));for(let i=0;i<50;i++){M.update(s,.01);M.update(restored,.01);}assert.deepEqual(restored,s);});

test('Tap targets stop at forehand/backhand contact without crossing the ball',()=>{for(const side of [-1,1]){const s=live();s.player.x=-side*2.7;s.ball.x=side*2.6;const target=M.ballTargetX(s);assert.ok(Math.abs(target-side*2.2)<1e-9);for(let i=0;i<100;i++){M.moveTowardBall(s,.037,2.4,target);assert.ok(side*s.player.x<=side*target+1e-9);}assert.equal(s.player.x,target);assert.ok(M.autoReturn(s));assert.ok(s.contactQuality>.99);assert.equal(s.lastHitSide,side);assert.equal(M.ballTargetX(s),null);}});
test('Tap uses the incoming contact location and the faster default stays bounded',()=>{const s=M.create();s.server=1;M.prepareServe(s);s.player.x=-2.7;M.beginServe(s);assert.equal(M.ballTargetX(s),1.15);M.movePlayer(s,1,.5);assert.ok(Math.abs(s.player.x+1.5)<1e-9);M.moveTowardBall(s,10,2.4,1.15);assert.equal(s.player.x,1.15);});

test('Opponent receives on a paddle outside and in front of its body',()=>{for(const shot of ['drive','dink','lob'])for(const x of [-2,2]){const s=live({mode:'rally'});M.hit(s,x,shot);const ready=M.cpuReadyPosition(s),fw=M.footwork({x:s.flight.contact.x-ready.x,y:s.flight.contact.y,z:s.flight.contact.z-ready.z},s.flight.cpuSide);const dx=s.flight.contact.x-ready.x,dz=s.flight.contact.z-ready.z;assert.ok(dz>=.4,'contact is in front of the robot');assert.ok(!(Math.abs(dx)<.46&&Math.abs(dz)<.36),'the ball cannot strike the robot body');assert.ok(Math.abs(fw.x)<1e-9&&Math.abs(fw.z)<1e-9&&fw.reachable,'ready position puts the ball in its stroke zone');s.cpu=ready;s.flight.time=s.flight.duration-.001;M.update(s,.01);assert.equal(s.flight.direction,'in');assert.deepEqual(s.cpuContact,s.flight.from);assert.equal(s.cpuStroke,shot==='lob'?'overhead':shot==='dink'?'low':x<0?'forehand':'backhand');}});
test('Quick contact completes a continuous bounced approach promptly once aligned',()=>{for(const bounced of [false,true]){const s=M.create();s.server=1;M.prepareServe(s);M.beginServe(s);s.player.x=s.flight.contact.x-.4;s.flight.time=s.flight.duration*(bounced?.75:.2);s.flight.bounced=bounced;s.ball=M.sampleFlight(s.flight,s.flight.time/s.flight.duration);assert.ok(M.requestQuickContact(s));let elapsed=0,maxStep=0,previous={...s.ball},sawBounce=bounced;while(s.phase==='flight'){M.update(s,.004,true,.01);elapsed+=.01;maxStep=Math.max(maxStep,Math.hypot(s.ball.x-previous.x,s.ball.y-previous.y,s.ball.z-previous.z));previous={...s.ball};sawBounce ||= s.lastEvent==='bounce';}assert.ok(elapsed<=(bounced?.24:.52));assert.ok(maxStep<.5);assert.ok(sawBounce);assert.equal(s.phase,'ready');assert.ok(M.autoReturn(s));}});
test('Quick contact cannot rescue an unaligned player or change an outgoing ball',()=>{const s=M.create();s.server=1;M.prepareServe(s);M.beginServe(s);s.player.x=-2.7;assert.equal(M.requestQuickContact(s),false);s.flight.direction='out';s.player.x=s.flight.contact.x;assert.equal(M.requestQuickContact(s),false);});
test('Score-free no-fail matches never award a point or a match win',()=>{for(const side of [0,1]){const s=live();s.scoreFree=true;s.server=side;s.score=[10,10];M.point(s,side,'Finished');assert.deepEqual(s.score,[10,10]);assert.equal(s.winner,null);assert.equal(s.phase,'point');}const s=live({mode:'rally'});M.hit(s,0);s.target={x:s.flight.to.x,z:s.flight.to.z};s.cpu=M.cpuReadyPosition(s);s.flight.time=s.flight.duration-.001;M.update(s,.01);assert.equal(s.stars,0);});

test('CPU footwork reaches every stroke; a robot out of lunge range misses',()=>{for(const shot of ['drive','dink','lob'])for(const x of [-2,2]){const s=live();M.hit(s,x,shot);s.cpu=M.cpuReadyPosition(s);assert.ok(M.cpuFootwork(s,s.flight.contact).reachable);s.cpu.x+=x>0?-.6:.6;assert.ok(M.cpuFootwork(s,s.flight.contact).reachable,'a late robot lunges');s.cpu.z-=2;assert.ok(!M.cpuFootwork(s,s.flight.contact).reachable);s.flight.time=s.flight.duration-.001;M.update(s,.01,false);assert.equal(s.phase,'point');assert.equal(s.lastEvent,'point');assert.deepEqual(s.score,[1,0]);}});
test('Arm segments are fixed and the lunge is capped; zones sit outside the body',()=>{assert.ok(M.ARM.upper>0&&M.ARM.lower>0);for(const side of [-1,1])for(const y of [.58,1,2.05]){const zone=M.strokeZone(side,y),centre=M.zoneCenter(side,y);assert.equal(Math.sign(centre.x),side,'zone centred on its own side');assert.ok(zone.x[1]-zone.x[0]>=.2&&zone.z[0]>.3);const far=M.footwork({x:side*(Math.abs(side<0?zone.x[0]:zone.x[1])+M.ARM.lunge.x+.05),y,z:(zone.z[0]+zone.z[1])/2},side);assert.equal(far.reachable,false);const near=M.footwork({x:side*(Math.abs(side<0?zone.x[0]:zone.x[1])+M.ARM.lunge.x-.05),y,z:(zone.z[0]+zone.z[1])/2},side);assert.equal(near.reachable,true);}});
test('Serve aim stays inside the legal diagonal service box',()=>{for(const points of [0,1,2,3]){const s=M.create();s.score[0]=points;M.prepareServe(s);const [lo,hi]=M.serveTargetBounds(s);assert.ok(lo<hi);assert.equal(Math.sign(lo+hi),-Math.sign(s.player.x));const near=Math.min(Math.abs(lo),Math.abs(hi)),far=Math.max(Math.abs(lo),Math.abs(hi));assert.ok(near<=.25&&far>=2.8&&far<3.05,'aim spans the whole box, centre line to sideline');assert.ok(lo*hi>0,'never into the other box');assert.ok(M.servePositions(s).cpu.z<=-6.7,'receiver waits at its baseline');assert.ok(s.serveAimX>=lo&&s.serveAimX<=hi);for(const wanted of [-9,lo,(lo+hi)/2,hi,9]){const t=JSON.parse(JSON.stringify(s));assert.ok(M.beginServe(t,.4,wanted));assert.ok(t.flight.to.x>=lo-1e-9&&t.flight.to.x<=hi+1e-9);assert.ok(t.flight.to.z<-5&&t.flight.to.z>-6.7,'lands deep in the box');if(wanted>=lo&&wanted<=hi)assert.ok(Math.abs(t.flight.to.x-wanted)<1e-9);}}});
test('Robot serves ignore any player aim',()=>{const s=M.create();s.server=1;M.prepareServe(s);s.serveAimX=2.6;assert.ok(M.beginServe(s,.4,-2.6));assert.equal(s.flight.direction,'serve');assert.ok(s.flight.to.z>2.13);});
