const {test}=require('node:test'),assert=require('node:assert/strict');
test('worker authorizes senders, owns only its tabs and never returns credentials',async()=>{
  const local={},session={},tabs=new Map([[7,{id:7,url:'http://127.0.0.1:4173/bennyshub/index.html',windowId:1}]]);const removed=[];let listener,allow=false,counter=20,windowState='normal',windowUpdates=0;
  const storage=data=>({async setAccessLevel(){},async get(k){return {[k]:data[k]};},async set(v){Object.assign(data,v);},async remove(k){for(const name of [].concat(k))delete data[name];}});
  global.chrome={storage:{local:storage(local),session:storage(session)},permissions:{async contains(){return allow;}},runtime:{id:'test-extension',getURL:p=>'chrome-extension://test-extension/'+p,onInstalled:{addListener(){}},onStartup:{addListener(){}},getManifest:()=>({version:'0.1.0'}),async openOptionsPage(){},onMessage:{addListener(fn){listener=fn;}}},tabs:{async create(o){const tab={id:counter++,windowId:1,...o};tabs.set(tab.id,tab);return tab;},async update(id,o){Object.assign(tabs.get(id),o);return tabs.get(id);},async get(id){const tab=tabs.get(id);if(!tab)throw Error('Missing tab');return {...tab,url:undefined};},async sendMessage(id){const tab=tabs.get(id);if(!tab)throw Error('Missing tab');return {url:tab.url};},async remove(id){removed.push(id);tabs.delete(id);},onRemoved:{addListener(){}}},windows:{async get(id){return {id,state:windowState};},async update(id,options){windowState=options.state;windowUpdates++;},async create(o){assert.equal(o.type,'popup');const tab={id:counter++,windowId:2,url:o.url};tabs.set(tab.id,tab);return {id:2,tabs:[tab]};}},action:{onClicked:{addListener(){}}}};
  await import('../extension/background.mjs');
  const hub={id:'test-extension',url:tabs.get(7).url,tab:tabs.get(7),frameId:0};
  const call=(action,payload={},sender=hub,protocol=1)=>new Promise(resolve=>listener({action,payload,protocol},sender,resolve));
  assert.equal((await call('HELLO')).ok,true);assert.equal((await call('HELLO',{},hub,2)).ok,false);
  assert.equal((await call('HELLO',{}, {...hub,url:'https://evil.example/bennyshub/'})).ok,false);
  assert.equal((await call('FETCH',{url:'https://evil.example'})).ok,false);
  assert.equal((await call('OPEN_STREAM',{url:'https://www.youtube.com/watch?v=test'})).ok,false);
  assert.equal(tabs.size,1);allow=true;
  assert.equal((await call('OPEN_STREAM',{url:'https://www.youtube.com/watch?v=test'})).ok,true);
  const player={id:'test-extension',url:'https://www.youtube.com/watch?v=test',tab:tabs.get(20),frameId:0};
  assert.equal((await call('PLAYER_HELLO',{},player)).ok,true);
  windowState='normal';const beforeReady=windowUpdates;
  assert.equal((await call('ENSURE_PLAYER_FULLSCREEN',{},player)).ok,true);
  assert.equal(windowState,'fullscreen');assert.equal(windowUpdates,beforeReady+1);
  assert.equal((await call('ENSURE_PLAYER_FULLSCREEN',{},player)).ok,true);
  assert.equal(windowUpdates,beforeReady+1); // Ensuring fullscreen must never toggle it off.
  assert.equal((await call('ENSURE_PLAYER_FULLSCREEN',{}, {...player,frameId:1})).ok,false);
  assert.equal((await call('ENSURE_PLAYER_FULLSCREEN',{}, {...player,tab:{id:99}})).ok,false);
  assert.equal((await call('ENSURE_PLAYER_FULLSCREEN')).ok,false);
  assert.equal((await call('PLAYER_HELLO',{}, {...player,tab:{id:99}})).ok,false);
  assert.equal((await call('RETURN_TO_HUB',{}, {...player,frameId:1})).ok,false);
  assert.equal((await call('RETURN_TO_HUB',{},player)).ok,true);assert.deepEqual(removed,[20]);
  const streaming={...hub,url:'http://127.0.0.1:4173/bennyshub/apps/tools/streaming/index.html'};
  assert.equal((await call('OPEN_STREAM',{url:'https://www.youtube.com/watch?v=first',trackProgress:true,playbackId:'test-playback'},streaming)).ok,true);
  const tracked={...player,tab:tabs.get(21),url:'https://www.youtube.com/watch?v=next'};
  const playerHello=await call('PLAYER_HELLO',{},tracked);assert.equal(playerHello.ok,true);assert.equal(playerHello.data.session.playbackId,undefined);
  assert.deepEqual((await call('STREAM_PROGRESS',{},streaming)).data,{playbackId:'test-playback',url:'https://www.youtube.com/watch?v=next'});
  assert.equal((await call('STREAM_PROGRESS')).ok,false);
  assert.equal((await call('STREAM_PROGRESS',{}, {...streaming,tab:{...streaming.tab,id:99}})).data,null);
  await call('PLAYER_HELLO',{}, {...tracked,url:'https://www.netflix.com/watch/123'});
  assert.equal((await call('STREAM_PROGRESS',{},streaming)).data.url,'https://www.youtube.com/watch?v=next');
  await call('PLAYER_HELLO',{}, {...tracked,url:'https://www.youtube.com/signin?code=private'});
  assert.equal((await call('STREAM_PROGRESS',{},streaming)).data.url,'https://www.youtube.com/watch?v=next');
  session.ai={provider:'openai',model:'test-model',key:'synthetic-test-key'};
  assert.equal((await call('AI_STATUS')).ok,false);
  assert.equal((await call('AI_GENERATE',{system:'test',input:'test'})).ok,false);
  assert.equal((await call('HELLO')).data.capabilities.includes('rt-convo'),false);
  delete global.chrome;
});
