(() => {
  let index=-1,press=null,hold,last=0;const speak=text=>{if(window.NarbeVoiceManager){NarbeVoiceManager.cancel();NarbeVoiceManager.speak(text);}else{speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text));}};
  function items(){const scope=document.querySelector('dialog[open]')||document;return [...scope.querySelectorAll('button,a,input,select,textarea')].filter(x=>!x.disabled&&x.getClientRects().length&&!x.closest('[data-scan-exclude]'));}
  function move(delta){const list=items();if(!list.length)return;const active=list.indexOf(document.activeElement);index=(active+delta+list.length)%list.length;document.querySelectorAll('.scan-current').forEach(x=>x.classList.remove('scan-current'));list[index].classList.add('scan-current');list[index].focus();speak(list[index].getAttribute('aria-label')||list[index].textContent||list[index].labels?.[0]?.textContent||'Text field');}
  const editable=e=>e.target.matches('input,textarea,select,[contenteditable=true]')||e.target.closest('[data-scan-exclude],[data-settings-dialog]');
  document.addEventListener('keydown',e=>{if(editable(e)||!['Space','Enter','NumpadEnter'].includes(e.code))return;e.preventDefault();const prefs=window.NarbeScanManager?.getSettings()||{};if(e.repeat||press||Date.now()-last<(prefs.inputSensitivity||50))return;press={code:e.code,back:false};if(e.code==='Space')hold=setTimeout(()=>{if(press){press.back=true;move(-1);}},3000);},true);
  document.addEventListener('keyup',e=>{if(editable(e)||!['Space','Enter','NumpadEnter'].includes(e.code))return;e.preventDefault();if(!press||press.code!==e.code)return;clearTimeout(hold);const p=press;press=null;last=Date.now();if(p.code==='Space'){if(!p.back)move(1);}else if(document.activeElement?.matches('button,a'))document.activeElement.click();else move(1);},true);
  addEventListener('blur',()=>{clearTimeout(hold);press=null;});let tick=0;setInterval(()=>{const p=window.NarbeScanManager?.getSettings();if(p?.autoScan&&!document.querySelector('[data-settings-dialog][open],[data-scan-exclude][open]')&&!document.hidden&&!press&&!document.activeElement?.matches('input,textarea,select')&&Date.now()-tick>=p.scanInterval){tick=Date.now();move(1);}},250);
  window.BennyUI={speak,back(){if(parent!==window)parent.postMessage({action: 'focusBackButton'},location.origin);else location.href='../../../index.html';},status(text){const el=document.getElementById('status');if(el)el.textContent=text;speak(text);}};
})();
