/** Objective language comes from placed pieces, not assumptions about a level. */
RT.levelBrief=(function(){'use strict';
const names={A:['princess','princesses'],v:['villager','villagers'],f:['fisher','fishers'],h:['healer','healers'],m:['merchant','merchants']};
function facts(level){const counts={};for(const layer of level.layers||[])for(const row of layer)for(const id of row)counts[id]=(counts[id]||0)+1;const protectedPeople=Object.entries(counts).filter(([id])=>RT.data.MAT[id]?.protected);const join=items=>items.length<3?items.join(' and '):items.slice(0,-1).join(', ')+', and '+items.at(-1);const people=join(protectedPeople.map(([id,n])=>n===1?(names[id]?.[0]||RT.data.MAT[id].name):n+' '+(names[id]?.[1]||RT.data.MAT[id].name)));return{people,protectedCount:protectedPeople.reduce((n,[,v])=>n+v,0),bars:Object.entries(counts).reduce((n,[id,v])=>n+(RT.data.MAT[id]?.prison?v:0),0),crates:Object.entries(counts).reduce((n,[id,v])=>n+(RT.data.MAT[id]?.pickup?v:0),0),crowns:counts.K||0};}
function goals(level){const raw=level.goals||{enemies:level.kingdomId?'guards':'crowns'};const enemies=raw.enemies||'none';if(!['guards','crowns','none'].includes(enemies))throw Error('Choose a valid guard goal.');const ids=(value,valid)=>{if(value===undefined)return[];if(!Array.isArray(value)||value.some(id=>!valid(id)))throw Error('Choose valid mission targets.');return [...new Set(value)];};return{enemies,destroy:ids(raw.destroy,id=>{const m=RT.data.MAT[id];return m&&!m.static&&!m.protected&&!m.guard&&!m.crown;}),collect:ids(raw.collect,id=>Object.values(RT.data.MAT).some(m=>m.pickup===id))};}
const allGuards=level=>goals(level).enemies==='guards';
const isTarget=(level,mat)=>{if(!mat)return false;const g=goals(level);return (g.enemies!=='none'&&!!mat.crown)||(g.enemies==='guards'&&!!mat.guard)||g.destroy.includes(mat.id);};
const isCollectTarget=(level,mat)=>!!mat?.pickup&&goals(level).collect.includes(mat.pickup);
function validateGoals(level){const g=goals(level),placed=level.layers.flat().join('');if(g.enemies==='none'&&!g.destroy.length&&!g.collect.length)throw Error('Choose at least one mission goal.');if(g.enemies!=='none'&&![...placed].some(id=>{const m=RT.data.MAT[id];return m?.crown||(g.enemies==='guards'&&m?.guard);}))throw Error(g.enemies==='guards'?'Add at least one guard.':'Add at least one crowned rascal (K).');for(const id of g.destroy)if(!placed.includes(id))throw Error('Place a '+RT.data.MAT[id].name+' for its destruction goal.');for(const id of g.collect)if(![...placed].some(ch=>RT.data.MAT[ch]?.pickup===id))throw Error('Place a '+RT.data.AMMO.find(a=>a.id===id).name+' crate for its collection goal.');return g;}
function goalText(level){const g=goals(level),parts=[];if(g.enemies!=='none')parts.push(g.enemies==='guards'?'Defeat every guard.':'Defeat every crowned guard.');for(const id of g.destroy)parts.push('Destroy every '+RT.data.MAT[id].name+'.');for(const id of g.collect)parts.push('Collect '+RT.data.AMMO.find(a=>a.id===id).name+' from a crate in this level.');return parts.join(' ')||'Choose mission goals.';}
function label(level){const g=goals(level);return g.destroy.length||g.collect.length?'Goals left':g.enemies==='guards'?'Guards left':'Crowns left';}
function instructions(level){const f=facts(level);return goalText(level)+(level.objective==='rescue'?(f.bars?' Break all the prison bars.':'')+(f.people?' Protect the shield-marked '+f.people+' from shots, fire and falling blocks.':''):'');}
function summary(level){const full=instructions(level);if(full.length<=180)return full;const g=goals(level),parts=[];if(g.enemies!=='none')parts.push(g.enemies==='guards'?'Defeat every guard.':'Defeat every crowned guard.');if(g.destroy.length)parts.push('Destroy '+g.destroy.length+' selected object types.');if(g.collect.length)parts.push('Collect '+g.collect.length+' selected ammo types.');if(level.objective==='rescue')parts.push('Protect every shield-marked friend'+(facts(level).bars?' and break prison bars.':'.'));return parts.join(' ');}
return{facts,instructions,summary,allGuards,isTarget,isCollectTarget,goals,validateGoals,label};})();
