/** Saved level scenery: decorative geometry stays outside the playable castle. */
RT.scenery=(function(){'use strict';
const presets=[
 ['meadow','Sunny meadow','Open grassland and wildflowers','#87b777'],['woodland','Woodland road','Tall trees along the old road','#426e52'],['harbor','Fishing harbor','Water, piers and little fishing boats','#6eb6c5'],['riverside','River bend','A winding river beside the castle','#73aab9'],['lake','Lakeside','Quiet water and a distant shore','#739faa'],['island','Island shore','A broad bay around the castle','#65b7c4'],['mountains','Mountain pass','Layered peaks above the valley','#929dac'],['farmland','Harvest fields','Golden fields and farm cottages','#c7a15b'],['orchard','Blossom orchard','Rows of round fruit trees','#db9cb2'],['village','Village outskirts','A cluster of warm roofed cottages','#c39772'],['ruins','Ancient ruins','Broken columns on a grassy hillside','#969d8d'],['marsh','Misty marsh','Reeds, pools and twisted trees','#7e9c88']
].map(([id,name,description,color])=>({id,name,description,color}));
const seasons=['spring','summer','autumn','winter'],times=['dawn','day','sunset','twilight','night'];
const propNames={trees:'Trees',rocks:'Rocks',buildings:'Cottages / ruins',boats:'Boats / docks',banners:'Banners',clouds:'Clouds'};
function defaults(preset='meadow'){return{preset,season:'summer',timeOfDay:'day',props:{trees:true,rocks:true,buildings:['harbor','farmland','village','ruins'].includes(preset),boats:['harbor','lake','island'].includes(preset),banners:['village','ruins'].includes(preset),clouds:true}};}
function validate(raw){if(raw===undefined)return defaults();if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Choose valid scene settings.');const e=defaults(raw.preset||'meadow');for(const [key,values] of [['preset',presets.map(p=>p.id)],['season',seasons],['timeOfDay',times]]){if(raw[key]!==undefined&&!values.includes(raw[key]))throw Error('Unknown scene '+key+'.');if(raw[key]!==undefined)e[key]=raw[key];}if(raw.props!==undefined){if(!raw.props||typeof raw.props!=='object'||Array.isArray(raw.props))throw Error('Choose valid background props.');for(const key of Object.keys(raw.props)){if(!Object.prototype.hasOwnProperty.call(propNames,key)||typeof raw.props[key]!=='boolean')throw Error('Unknown background prop.');e.props[key]=raw.props[key];}}return e;}
function apply(h,level,base,g){
 const e=validate(level.environment);h.environment=e;const flat=base.flat,scene=h.ground.parent;
 const season={spring:{ground:'#8fbc80',leaf:e.preset==='orchard'?'#e6b3c8':'#7cab72'},summer:{ground:base.ground,leaf:base.hill},autumn:{ground:'#aeaa70',leaf:'#c98e55'},winter:{ground:'#e3e9df',leaf:'#e3eee7'}}[e.season];
 const sky={dawn:['#8486bc','#e4b7a0','#f8dfb0'],day:[base.sky1,base.sky2,base.sky3||base.sky2],sunset:['#807ca9','#e7b095','#f3cc99'],twilight:['#536282','#929bb0','#bbc0c0'],night:['#152c4b','#354c70','#78889b']}[e.timeOfDay];
 const p={...base,ground:flat?base.ground:season.ground,hill:flat?base.hill:season.leaf};const colors=flat?[base.sky1,base.sky2,base.sky3||base.sky2]:sky;
 h.skyMat.map?.dispose();h.skyMat.map=RT.art.skyTexture(...colors);scene.background=new THREE.Color(colors[1]);scene.fog=flat?null:new THREE.Fog(colors[1],55,240);
 h.ground.material=RT.art.paper(p.ground,{roughness:1});h.groundMat=h.ground.material;h.hemi.color.set(flat?base.sky1:'#dfebfa');h.hemi.groundColor.set(p.ground);
 const night=e.timeOfDay==='night';h.hemi.intensity=night?1.35:1.7;h.amb.intensity=night?.75:.55;h.sun.intensity=night?1.7:e.timeOfDay==='twilight'?1.9:2.5;h.sun.color.set(flat?base.sunColor:night?'#bfdbff':['sunset','dawn'].includes(e.timeOfDay)?'#ffe1be':base.sunColor);
 RT.art.repaint(h.hills,p);h.garden.visible=false;h.clouds.visible=e.props.clouds&&!flat;
 const parts=RT.levels.parseLevel(level).blocks,bounds={left:-5,right:5,back:-level.dist-4};for(const b of parts){bounds.left=Math.min(bounds.left,b.x-b.w/2);bounds.right=Math.max(bounds.right,b.x+b.w/2);bounds.back=Math.min(bounds.back,b.z-b.d/2);}
 const side=Math.max(Math.abs(bounds.left),bounds.right)+10,back=bounds.back-16,rand=RT.util.rng(RT.util.hash('scene-'+e.preset));
 const mats=new Map();function material(color,glow=false){const key=color+'-'+glow;if(!mats.has(key))mats.set(key,flat||glow?new THREE.MeshBasicMaterial({color}):new THREE.MeshStandardMaterial({color,roughness:.85}));return mats.get(key);}
 function mesh(geo,color,x,y,z,parent=g,kind='',glow=false){const m=new THREE.Mesh(geo,material(color,glow));m.position.set(x,y,z);m.castShadow=!glow;m.receiveShadow=!glow;m.userData.scenery=kind;parent.add(m);return m;}
 function box(w,hh,d,color,x,y,z,parent=g,kind=''){return mesh(new THREE.BoxGeometry(w,hh,d),color,x,y,z,parent,kind);}
 const wood=flat?'#ffffff':'#86654b',leaf=flat?'#476747':season.leaf,water=flat?'#125b72':night?'#345e83':e.preset==='marsh'?'#6c9b91':'#66acbb';
 function pool(x,z,w,d){box(w,.028,d,flat?'#eeeecc':'#cebd96',x,.01,z,g,'shore');box(w-1,.03,d-1,water,x,.04,z,g,'water');for(let i=0;i<12;i++)box(rand.range(1.2,4),.012,.1,flat?'#74d9ef':'#addad5',x+rand.range(-w*.4,w*.4),.065,z+rand.range(-d*.42,d*.42),g,'ripple');}
 const wet=['harbor','riverside','lake','island','marsh'].includes(e.preset);
 if(wet){if(e.preset==='riverside'){for(let i=0;i<5;i++)pool(side+9+Math.sin(i)*3,-i*24,17,27);}else if(e.preset==='marsh'){for(let i=0;i<6;i++)pool((i%2?-1:1)*(side+8+i*2),back-i*8,18,14);}else{pool(side+30,-level.dist-10,60,130);if(e.preset!=='harbor')pool(0,back-50,180,65);if(e.preset==='island')pool(-side-30,-level.dist-20,60,120);}}
 function tree(x,z,size=1){const root=new THREE.Group();root.position.set(x,0,z);root.scale.setScalar(size);root.userData.scenery='tree';g.add(root);mesh(new THREE.CylinderGeometry(.26,.4,3,7),wood,0,1.5,0,root);if(e.preset==='mountains'||e.preset==='woodland'){for(let j=0;j<3;j++)mesh(new THREE.ConeGeometry(2-j*.4,2.7,8),leaf,0,3+j,0,root);}else mesh(new THREE.IcosahedronGeometry(2.2,1),leaf,0,3.9,0,root);}
 if(e.props.trees){const count=['woodland','orchard','marsh'].includes(e.preset)?34:14;for(let i=0;i<count;i++){const sign=wet&&e.preset!=='marsh'?-1:i%2?-1:1;tree(sign*(side+rand.range(2,25)),back+rand.range(-38,15),rand.range(.8,1.6));}}
 if(e.props.rocks)for(let i=0;i<18;i++){const sign=wet?-1:i%2?-1:1;mesh(new THREE.DodecahedronGeometry(rand.range(.5,1.5),0),flat?'#aeb5bb':e.season==='winter'?'#d9e2e4':'#9a9e91',sign*(side+rand.range(0,30)),.5,back+rand.range(-25,12),g,'rock');}
 function cottage(x,z,i){const root=new THREE.Group();root.position.set(x,0,z);root.rotation.y=.1*(i%3-1);root.userData.scenery='building';g.add(root);box(4,3,3,flat?'#eeeecc':'#d9bf91',0,1.5,0,root);const roof=mesh(new THREE.ConeGeometry(3.6,2.5,4),e.season==='winter'?'#e4ecea':flat?'#59636e':'#9c6958',0,4,0,root);roof.rotation.y=Math.PI/4;box(.8,1.5,.1,wood,0,.75,1.55,root);for(const x of [-1.2,1.2])box(.55,.65,.12,night?'#ffe6a0':'#60838a',x,1.9,1.56,root);box(.5,1.8,.55,wood,1.2,4.1,-.7,root);}
 if(e.props.buildings)for(let i=0;i<5;i++){const x=-side-5-i*6,z=back-(i%2)*7;if(e.preset==='ruins'){for(let j=0;j<3;j++)mesh(new THREE.CylinderGeometry(.5,.6,2+j,8),'#b9b7a2',x+j*1.5,1+j*.5,z,g,'building');box(5,.8,1.3,'#a0a591',x+1,3,z,g,'building');}else cottage(x,z,i);}
 if(e.props.boats&&wet){for(let i=0;i<3;i++){const x=side+6+i*8,z=-level.dist-8-i*12;const boat=new THREE.Group();boat.position.set(x,.2,z);boat.rotation.y=.25;boat.userData.scenery='boat';g.add(boat);const hull=mesh(new THREE.SphereGeometry(1,10,6),wood,0,.3,0,boat);hull.scale.set(1.2,.55,2.8);box(.12,4,.12,wood,0,2.1,0,boat);const sail=new THREE.Shape();sail.moveTo(.1,0);sail.lineTo(.1,3);sail.lineTo(2,0);sail.closePath();const cloth=mesh(new THREE.ShapeGeometry(sail),'#f4e6c2',0,1,0,boat);cloth.material.side=THREE.DoubleSide;for(let j=0;j<12;j++)box(.5,.16,1.7,wood,side-2+j*.6,.18,z+3,g,'dock');for(let j=0;j<3;j++)box(.2,1,.2,wood,side+j*2,.45,z+3.8,g,'dock');}}
 if(e.props.banners)for(const sign of [-1,1]){box(.15,5,.15,wood,sign*side,2.5,back+10,g,'banner');box(1.4,1.9,.08,flat?'#ffff77':'#b87572',sign*side+.7,3.8,back+10,g,'banner');}
 if(e.preset==='mountains')for(let i=0;i<9;i++){const x=(i-4)*17,z=back-45-Math.abs(i-4)*3,hh=18+rand.range(0,15);mesh(new THREE.ConeGeometry(16,hh,5),'#879aa3',x,hh/2,z,g,'mountain');mesh(new THREE.ConeGeometry(5,hh*.32,5),'#e5e9df',x,hh*.84,z,g,'snowcap');}
 if(e.preset==='farmland')for(let i=0;i<12;i++)box(1.3,.1,24,e.season==='winter'?'#eef0e5':'#d3b96b',-side-3-i*1.8,.08,-level.dist-3,g,'field');
 if(e.preset==='marsh')for(let i=0;i<35;i++)box(.09,rand.range(1,2),.09,'#b8aa78',(i%2?-1:1)*(side+rand.range(1,10)),.6,back+rand.range(-20,20),g,'reed');
 if(['night','twilight'].includes(e.timeOfDay)&&!flat){mesh(new THREE.SphereGeometry(3.4,18,12),'#f6ecc9',30,48,back-90,g,'moon',true);for(let i=0;i<75;i++)mesh(new THREE.SphereGeometry(rand.range(.09,.2),4,3),'#fff1d0',rand.range(-110,110),rand.range(40,100),back-rand.range(40,130),g,'star',true);}
}
function inspect(h){const counts={};h.levelScenery?.traverse(o=>{const k=o.userData.scenery;if(k)counts[k]=(counts[k]||0)+1;});return{environment:h.environment,counts,sky:h.ground.parent.background.getHexString(),light:h.amb.intensity};}
return{presets,seasons,times,propNames,defaults,validate,apply,inspect};})();
