/* CHOICE: menus and Serve/Pause. MECHANIC: positioning and automatic paddle returns. */
'use strict';
const $=id=>document.getElementById(id),M=RallyModel,sm=NarbeScanManager,vm=NarbeVoiceManager;
const STORE='narbe-rally-club-v1',defaults={playStyle:'manual',moveSpeed:2.4,noHold:false,pace:.65,assist:true,reduceMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,sound:true};
let settings={...defaults},stats={wins:0,best:0,stars:0,nextOpponent:0},saved=null;
try{const raw=JSON.parse(localStorage.getItem(STORE)||'{}');for(const key of Object.keys(defaults))if(typeof raw.settings?.[key]===typeof defaults[key])settings[key]=raw.settings[key];for(const key of Object.keys(stats))if(Number.isFinite(raw.stats?.[key])&&raw.stats[key]>=0)stats[key]=raw.stats[key];saved=raw.saved;}catch{}
settings.playStyle=['manual','one','assisted'].includes(settings.playStyle)?settings.playStyle:'manual';settings.moveSpeed=({1.2:1.6,1.8:2.4,2.6:3.4})[settings.moveSpeed]||settings.moveSpeed;settings.moveSpeed=[1.6,2.4,3.4].includes(settings.moveSpeed)?settings.moveSpeed:2.4;settings.pace=[0,.4,.65,1].includes(settings.pace)?settings.pace:.65;stats.nextOpponent=Number.isInteger(stats.nextOpponent)&&stats.nextOpponent<M.OPPONENTS.length?stats.nextOpponent:0;
let state=M.create(),view='menu',returnView='menu',pausedView=null,scene,choice,lastFrame=performance.now(),lastEvent=-1,lastPhase=-1,feedbackUntil=0,lastAimRegion='',checkpointTime=0;
const keys={Space:false,Enter:false};let spaceTimer=null,spaceRepeat=null,enterTimer=null,spaceHeld=false,braking=false,enterHeld=false,enterAt=0,pointerId=null,pointerRole=null,pointerStartX=0,pointerStartPlayer=0,movePointer=0,arrowPointer=null,chargeStart=null,chargeTier='',moveKey=null,moveLatched=false,tapTarget=null,pointerTarget=null,contactIntent=false,pauseGestureKey=null;
function speak(text){return vm.speak(text);}
function save(){try{localStorage.setItem(STORE,JSON.stringify({settings,stats,saved}));}catch{}}
function checkpoint(){if(['play','aim','manual','flight','serve','serveAim','pause'].includes(view)&&state.phase!=='over'){saved=JSON.parse(JSON.stringify(state));save();}}
function sound(name){if(settings.sound)SafeAudio.play(name,.4);}
for(const name of ['select','hover','score','win','lose','bank'])SafeAudio.preload(name);
function isAssisted(){return settings.playStyle==='assisted';}
function isOneSwitch(){return settings.playStyle==='one'||settings.playStyle==='manual'&&sm.getSettings().autoScan;}
function automaticServeAim(){return isOneSwitch()||settings.noHold||isAssisted();}
function noFail(){return state.mode==='rally'||settings.pace===0;}
function activeGame(){return ['play','aim','manual','flight','serve','serveAim'].includes(view);}
function canSetUp(){return state.phase==='serve'&&state.server===0||['ready','aim'].includes(state.phase)||state.flight&&state.flight.direction!=='out';}
function ballVisible(){return !!scene?.isBallVisible(state.ball);}
function updateControls(){
$('controlHint').innerHTML=sm.getSettings().autoScan?'<kbd>ENTER</kbd> Choose · Auto Scan on':'<kbd>SPACE</kbd> Move <kbd>ENTER</kbd> Choose';
const serving=state.phase==='serve';$('serveKit').hidden=!serving;
$('serveButton').innerHTML='<span>↗</span>'+(view==='serveAim'?'Serve now':state.server===0?'Your serve':'Receive serve');
$('courtHint').textContent=view==='serveAim'?(automaticServeAim()?'Aim sweeps · Press ENTER to stop it, release to serve':'Hold SPACE to aim · Each hold reverses · ENTER serves'):serving?(sm.getSettings().autoScan?'Serve / Pause · ENTER selects':'SPACE chooses Serve / Pause · ENTER selects'):isAssisted()?'Automatic movement & returns · Hold ENTER 6 seconds to pause':settings.noHold?(isOneSwitch()?'Tap ENTER to reach the ball · Stops in position':'Tap SPACE or ENTER to reach the ball · Stops in position'):isOneSwitch()?'Hold ENTER toward the return · Release stops':'Hold SPACE ← · Hold ENTER → · Automatic paddle';
$('courtSurface').setAttribute('aria-label',isAssisted()?'Court. Automatic movement and returns. Tap to pause.':'Court. Drag to move toward the ball. Your paddle returns it automatically.');
}
function oneSwitchDirection(){const f=state.flight,incoming=f&&f.direction!=='out';if(incoming||['ready','aim'].includes(state.phase)){const x=incoming?(f.contact||f.to).x:state.ball.x,dx=x-state.player.x;return Math.abs(dx)<=.45?0:Math.sign(dx);}return state.moveDir===-1?1:-1;}
function updateDirectionCue(){
const cue=$('directionCue'),visible=view==='manual'&&isOneSwitch()&&!isAssisted()&&!settings.noHold&&state.phase!=='serve';
if(cue.hidden===visible)cue.hidden=!visible;if(!visible)return;
const holding=!!(moveKey&&keys[moveKey]),direction=holding?state.moveDir:oneSwitchDirection(),cueState=(holding?'held:':'next:')+direction;
if(cue.dataset.state===cueState)return;cue.dataset.state=cueState;cue.dataset.direction=direction;cue.classList.toggle('is-held',holding);
$('directionArrow').textContent=direction===0?'●':direction<0?'←':'→';$('directionAction').textContent=direction===0?'IN POSITION':holding?'HOLDING':'NEXT HOLD';$('directionLabel').textContent=direction===0?'READY':direction<0?'LEFT':'RIGHT';
}
function cancelCharge(){chargeStart=null;state.chargePower=null;}
function clearKeys(){clearTimeout(spaceTimer);clearInterval(spaceRepeat);clearTimeout(enterTimer);spaceTimer=spaceRepeat=enterTimer=null;keys.Space=keys.Enter=false;moveKey=null;moveLatched=false;tapTarget=null;pointerTarget=null;contactIntent=false;pauseGestureKey=null;enterAt=0;spaceHeld=braking=enterHeld=false;movePointer=0;state.aimFrozen=false;cancelCharge();if(pointerId!==null){const id=pointerId;pointerId=null;try{$('courtSurface').releasePointerCapture(id);}catch{}}pointerRole=null;if(arrowPointer){const p=arrowPointer;arrowPointer=null;try{p.element.releasePointerCapture(p.id);}catch{}}$('holdRing').classList.remove('active');choice?.cancelInput();}

function scan(items,key,host,fresh=true){choice.sync({key,items,statusHost:host},{fresh});}
function stopScan(){choice.sync(null);for(const el of document.querySelectorAll('.scan-focus'))el.classList.remove('scan-focus');}
function button(item,parent){const el=document.createElement('button');el.id='action-'+item.id;el.className=item.primary?'primary':'';const label=document.createElement('span');label.textContent=item.title;if(item.detail){const detail=document.createElement('small');detail.textContent=item.detail;label.append(detail);}el.append(label);if(parent===$('menuItems')){const arrow=document.createElement('span');arrow.className='arrow';arrow.textContent=item.primary?'↗':'›';arrow.setAttribute('aria-hidden','true');el.append(arrow);}el.onclick=()=>{choice.align(item.id);activate(item);};parent.append(el);return {...item,element:el,labelElement:label,label:item.label||[item.title,item.detail].filter(Boolean).join('. ')};}
function activate(item){sound('select');item.action();}
function screen(key,title,description,entries,{hint='',eyebrow='NARBE RALLY CLUB',fresh=true}={}){if(fresh){clearKeys();for(const el of document.querySelectorAll('.scan-focus'))el.classList.remove('scan-focus');window.scrollTo(0,0);}view=key==='home'?'menu':key;document.body.classList.toggle('submenu',key!=='home');document.body.classList.remove('playing');$('menu').hidden=false;$('play').hidden=true;$('pauseButton').hidden=true;$('title').className=key==='home'?'':'small';$('title').innerHTML=key==='home'?'Find your<br><em>rally.</em>':'';if(key!=='home')$('title').textContent=title;$('eyebrow').textContent=eyebrow;$('description').textContent=description;$('menuHint').textContent=hint;$('menuItems').replaceChildren();scan(entries.map(it=>button(it,$('menuItems'))),key,$('menuStatus'),fresh);if(fresh)choice.announce(key==='home'?'NARBE Robot Pickleball. Play a match or a relaxed rally.':title+'. '+description);updateControls();}
function home(){screen('home','Rally Club','Step onto the court. Find your angle. Make it a rally.',[
...(saved?[{id:'resume',title:'Resume your rally',detail:'Pick up where you left off',primary:true,action:resumeSaved}]:[]),
{id:'match',title:'Play a match',detail:'Robot singles · 11 points, win by 2',primary:!saved,action:()=>newGame('match')},
{id:'rally',title:'Just rally',detail:'No-fail · Ball waits · Serve/Pause every six returns',action:()=>newGame('rally')},
{id:'settings',title:'Settings',detail:'Movement, pace & access',action:()=>openSettings('menu')},
{id:'about',title:'How to play & credits',action:help},{id:'exit',title:'Back to Hub',action:exit}
],{eyebrow:'A LITTLE COURT. A BIG FEELING.',hint:stats.wins+' matches won · '+stats.best+' best rally'});}
function confirm(title,description,action,back){screen('confirm',title,description,[{id:'cancel',title:'Go back',primary:true,action:back},{id:'confirm',title:'Continue',action}]);}
function newGame(mode){if(saved){confirm('Start a new rally?','This will replace your saved rally.',()=>start(mode),home);return;}start(mode);}
function start(mode,opponent=stats.nextOpponent){state=M.create({mode,opponent,controlMode:settings.playStyle});lastEvent=-1;lastPhase=-1;checkpointTime=0;pausedView=null;M.prepareServe(state);gameVisible();showServe();}
function showServe(){lastPhase=state.phaseId;clearKeys();view='serve';updateControls();hud();scan([{id:'serve',title:state.server===0?'Your serve':'Receive serve',label:state.server===0?'Your serve':'Receive serve',element:$('serveButton'),action:chooseServe},{id:'pause',title:'Pause',label:'Pause / options',element:$('servePause'),action:pause}],'serve-choice',$('playStatus'));choice.announce(state.message);checkpoint();}
function openServeAim(){clearKeys();stopScan();view='serveAim';state.serveAiming=true;const bounds=M.serveTargetBounds(state);state.serveAimX=M.clamp(Number.isFinite(state.serveAimX)?state.serveAimX:(bounds[0]+bounds[1])/2,...bounds);state.serveAimDir=state.serveAimDir===-1?-1:1;state.serveAimFrozen=false;updateControls();speak(automaticServeAim()?'Aim is moving. Press Enter to stop it, then release to serve.':'Hold Space to move your aim. Each new hold goes the other way. Press Enter to serve.');checkpoint();}
function chooseServe(){if(state.phase!=='serve')return;if(state.server===0&&view!=='serveAim')openServeAim();else commenceServe();}
function commenceServe(power=.4){if(!M.beginServe(state,Number.isFinite(power)?power:.4,state.serveAimX))return;state.serveAiming=state.serveAimFrozen=false;clearKeys();stopScan();view=isAssisted()?'flight':'manual';updateControls();speak(state.server===0?'You serve.':'Robot serves.');sound('bank');checkpoint();}
function validSave(s){return s&&['serve','ready','aim','flight','point'].includes(s.phase)&&Array.isArray(s.score)&&s.score.length===2&&s.score.every(n=>Number.isFinite(n)&&n>=0)&&['player','cpu','ball'].every(k=>s[k]&&['x','z'].every(n=>Number.isFinite(s[k][n])))&&Number.isFinite(s.ball.y)&&[0,1,2].includes(s.opponent)&&['rally','match'].includes(s.mode)&&s.swings&&Number.isFinite(s.event)&&M.SHOTS[s.shot]&&Number.isFinite(s.aim)&&Number.isFinite(s.rally)&&((s.phase==='flight')===!!s.flight)&&(!s.flight||s.flight.from&&s.flight.to&&Number.isFinite(s.flight.duration)&&s.flight.duration>0);}
function resumeSaved(){if(!validSave(saved)){saved=null;save();home();return;}state=JSON.parse(JSON.stringify(saved));if(state.rulesVersion!==3){state.rulesVersion=3;state.server=state.server===1?1:0;state.rallyClosed=['serve','point'].includes(state.phase);state.pendingShot=null;delete state.manualStep;}lastPhase=-1;lastEvent=state.event;restoreGame();}
function gameVisible(){clearKeys();for(const el of document.querySelectorAll('.scan-focus'))el.classList.remove('scan-focus');window.scrollTo(0,0);$('menuItems').replaceChildren();document.body.classList.add('playing');document.body.classList.remove('submenu');$('menu').hidden=true;$('play').hidden=false;$('pauseButton').hidden=false;hud();}
function showReady(){stopScan();const liningUp=settings.noHold&&!isAssisted()&&moveLatched&&noFail();if(!liningUp&&ballVisible()&&M.autoReturn(state)){moveLatched=false;tapTarget=null;contactIntent=false;view=isAssisted()?'flight':'manual';sound('bank');updateControls();checkpoint();}else if(noFail()){if(state.phase==='ready'){state.phase='aim';updateControls();speak('Ball waiting. Move toward it.');checkpoint();}}else{M.miss(state);moveLatched=false;tapTarget=null;view=isAssisted()?'flight':'manual';updateControls();checkpoint();}}

function pause(){if(!activeGame())return;pausedView=view;checkpoint();pauseScreen();}
function pauseScreen(fresh=true){screen('pause','Take a breather.','Your rally is right where you left it.',[{id:'continue',title:'Continue rally',action:restoreGame},{id:'settings',title:'Settings',action:()=>openSettings('pause')},{id:'restart',title:'Restart',action:()=>confirm('Restart this rally?','Your current score will be cleared.',()=>{saved=null;start(state.mode,state.opponent);},pauseScreen)},{id:'home',title:'Main menu',detail:'Your rally is saved',action:home},{id:'exit',title:'Back to Hub',action:exit}],{fresh});}
function restoreGame(){lastPhase=state.phaseId;if(state.controlMode!==settings.playStyle)state.pendingShot=null;state.controlMode=settings.playStyle;state.moveDir=state.moveDir===-1?-1:1;gameVisible();if(state.phase==='serve'){if(state.serveAiming&&state.server===0)openServeAim();else showServe();return;}if(!isAssisted()){view='manual';stopScan();updateControls();}else if(state.phase==='flight'||state.phase==='point'){view='flight';stopScan();updateControls();}else{state.pendingShot=null;view='flight';stopScan();updateControls();}speak('Rally resumed.');}
function openSettings(back='menu',refresh=false){returnView=back;const toggle=key=>()=>{settings[key]=!settings[key];save();openSettings(returnView,true);};const cycle=(key,values)=>()=>{settings[key]=values[(values.indexOf(settings[key])+1)%values.length];save();openSettings(returnView,true);};screen('settings','Your kind of rally.','Access settings and game challenge are yours to choose.',[
{id:'play-style',title:'Controls: '+(isAssisted()?'Automatic':isOneSwitch()?'One switch':'Two switches'),detail:isAssisted()?'Your robot moves and returns for you':isOneSwitch()?'Each new Enter press heads toward the incoming ball':'Space moves left · Enter moves right',action:cycle('playStyle',sm.getSettings().autoScan?['manual','assisted']:['manual','one','assisted'])},
{id:'no-hold',title:'Movement input: '+(settings.noHold?'Tap — no hold':'Hold to move'),detail:settings.noHold?'Tap to reach the incoming ball, then stop automatically':'Release your switch to stop moving',action:toggle('noHold')},
{id:'move-speed',title:'Movement: '+(settings.moveSpeed===1.6?'Relaxed':settings.moveSpeed===2.4?'Steady':'Brisk'),detail:'Left / right movement speed',action:cycle('moveSpeed',[1.6,2.4,3.4])},
{id:'tts',title:'Speech: '+(vm.getSettings().ttsEnabled?'On':'Off'),action:()=>{vm.toggleTTS();openSettings(returnView,true);}},
{id:'voice',title:'Voice',detail:vm.getVoiceDisplayName()||'Default',action:()=>{vm.cycleVoice();openSettings(returnView,true);}},
{id:'pace',title:'Ball pace: '+(settings.pace===0?'No-fail':settings.pace===.4?'Slow motion':settings.pace===.65?'Relaxed':'Full speed'),detail:settings.pace===0?'Ball stops until you reach it':settings.pace===1?'Real-time ball flight · Get there quickly':'Extra time as the ball approaches your paddle',action:cycle('pace',[.4,.65,1,0])},
{id:'motion',title:'Reduced motion: '+(settings.reduceMotion?'On':'Off'),detail:'No confetti, trails or idle animation',action:toggle('reduceMotion')},
{id:'auto',title:'Auto Scan: '+(sm.getSettings().autoScan?'On · One switch':'Off · Two switches'),action:()=>{sm.toggleAutoScan();}},
{id:'scan-speed',title:'Scan speed: '+sm.getScanInterval()/1000+' seconds',action:()=>{sm.cycleScanSpeed();}},
{id:'sound',title:'Sound effects: '+(settings.sound?'On':'Off'),action:toggle('sound')},
{id:'back',title:'Back',primary:true,action:()=>returnView==='pause'?pauseScreen():home()}
],{fresh:!refresh,hint:'The paddle hits automatically. Hold mode: two switches move left/right; each new one-switch Enter press heads toward the incoming ball. Tap mode moves to the ball and stops. Serve and Pause are offered between every rally; your serve then aims inside the legal box. Holding Enter six seconds also pauses; One switch accepts a Space hold too.'});if(refresh)choice.announce(choice.context.items.find(x=>x.id===choice.getState()?.id)?.label||'Setting updated');}
function help(){screen('about','Keep the rally alive.','Reach the ball. Your robot takes the shot.',[
{id:'read',title:'Hear how to play',action:()=>choice.announce('Choose Your serve to aim. In Two switches, hold Space to move the serve target and release to stop; each new hold goes the other way. Press Enter to serve. In One switch and Tap modes the target sweeps by itself; press Enter to stop it where you want, and release to serve. The target always stays in the legal diagonal service box, which glows while you aim. The robot serves without any aiming. During rallies, in Two switches, hold Space to move left and Enter to move right. Release to stop. In One switch, each new Enter press chooses the direction toward the ball coming back from the opponent. Hold to move and release to stop. The arrow shows the direction of your next hold. If you are already lined up, it says Ready. The Hub Auto Scan setting also enables this Enter-only control. Your paddle automatically uses forehand or backhand when the ball bounces into reach. Better positioning produces a stronger return. There are no shot selections or charges. Enable Tap movement if holding is difficult. Tap Enter, or Space with two switches, to move to the incoming ball and stop in position. Tap again for each return. The robot handles deep and short balls and diving reaches automatically. Serve and Pause are offered before every rally. Hold Enter six seconds to pause during play, or Space in One switch. Mouse and touch can drag on the court. Full speed is quicker and harder. Reach the ball before it passes you. No-fail stops the ball until you reach it. No-fail and Just rally take a Serve or Pause break every six returns.')},
{id:'rules',title:'Singles rules',detail:'Only the server scores · 11 points, win by 2',action:()=>choice.announce('Only the server earns points. If the server loses the rally, service changes with no point awarded. Serve diagonally from the right when your score is even, left when odd. Both the serve and return must bounce. This game plays ground strokes, so there are no kitchen volleys. Games go to eleven, win by two. Slow motion gives you time to reach the ball. Just rally is score-free practice.')},
{id:'credits',title:'Credits & original game',action:credits},{id:'back',title:'Back',action:home}
],{hint:'Singles: 11 points, win by 2. Only the server scores. Slow motion and generous paddle reach are accessibility aids.'});}

function credits(){screen('credits','Where this rally began.','In collaboration with SCSU and student creator Lily Flack. Redesigned and developed by NARBE.',[
{id:'original',title:'Play Lily’s original',detail:'The original Pickleball Rally is preserved',action:()=>confirm('Open the original game?','This opens Lily’s original Pickleball Rally. Your NARBE rally stays saved. Return through the Hub to NARBE Pickleball.',()=>{checkpoint();location.href='../PICKLEBALLRALLY/index.html';},credits)},
{id:'back',title:'Back',primary:true,action:help}
],{hint:'A new implementation inspired by Pickleball Rally. Court, characters, controls and gameplay created for this version. Built with Three.js (MIT).'});}
function exit(){checkpoint();speak('Back to Hub.');if(window.parent!==window)window.parent.postMessage({action:'focusBackButton'},'*');else location.href='../../../index.html';}
function hud(){document.querySelector('.scoreboard').hidden=noFail();$('rallyLabel').textContent=noFail()?'UNTIL BREAK':'RALLY';$('playerScore').textContent=state.mode==='rally'?state.stars:state.score[0];$('cpuScore').textContent=state.mode==='rally'?state.best:state.score[1];$('playerLabel').textContent=state.mode==='rally'?'STARS':'YOU';$('opponentLabel').textContent=state.mode==='rally'?'BEST RALLY':M.OPPONENTS[state.opponent].name.toUpperCase();$('modeLabel').textContent=state.mode==='rally'?'JUST RALLY':state.server===0?'SERVER: YOU':'SERVER: ROBOT';$('rallyCount').textContent=state.mode==='rally'?'BREAK EVERY 6':'11 · WIN BY 2';$('rallyValue').textContent=noFail()?Math.max(0,6-state.rally):state.rally;$('bestValue').textContent='BEST '+Math.max(state.best,stats.best);}
function result(){if(state.phase!=='over')return;const won=state.winner===0,summary=(won?'Match won! ':'Match complete. ')+state.score[0]+'–'+state.score[1]+'. Next match ready.';stats.best=Math.max(stats.best,state.best);if(won)stats.wins++;stats.nextOpponent=(state.opponent+1)%M.OPPONENTS.length;saved=null;save();sound(won?'win':'lose');start('match');$('feedback').textContent=summary;feedbackUntil=performance.now()+4500;speak(summary+' Serve when you are ready.');}
function lostInput(){clearKeys();if(activeGame())pause();}
choice=NarbeChoiceScanAdapter.create({holdThreshold:3000,stateHost:document.body,speak,
onHighlight(item,scanState,ctx){for(const i of ctx.items)i.element?.classList.toggle('scan-focus',i.id===item?.id);if(item){if(!activeGame())item.element?.scrollIntoView({block:'nearest',behavior:'instant'});}else if(ctx.items.some(i=>i.element===document.activeElement))document.activeElement.blur();},onSelect:activate});
$('pauseButton').onclick=pause;$('brand').onclick=e=>{e.preventDefault();if(activeGame())pause();else home();};
$('serveButton').onclick=chooseServe;$('servePause').onclick=pause;
const court=$('courtSurface');
function pointMove(e){if(view==='serveAim'){const target=scene.aimAt(e.clientX,e.clientY,M.SERVE_DEPTH);if(Number.isFinite(target))state.serveAimX=M.clamp(target,...M.serveTargetBounds(state));return;}if(view!=='manual'||state.phase==='serve')return;moveLatched=false;tapTarget=null;pointerTarget=M.clamp((e.clientX/innerWidth-.5)*5.4,-2.7,2.7);}
court.addEventListener('pointerdown',e=>{if(e.button!==0||pointerId!==null||!activeGame())return;e.preventDefault();pointerId=e.pointerId;court.setPointerCapture(pointerId);pointerRole=view==='serveAim'?'serveAim':state.phase==='serve'?'serve':isAssisted()?'pause':'move';startPauseHold();if(pointerRole==='move'||pointerRole==='serveAim')pointMove(e);});
court.addEventListener('pointermove',e=>{if(pointerId===e.pointerId&&(pointerRole==='move'||pointerRole==='serveAim'))pointMove(e);});
court.addEventListener('pointerup',e=>{if(e.pointerId!==pointerId)return;e.preventDefault();const role=pointerRole;pointerId=null;pointerRole=null;court.releasePointerCapture(e.pointerId);clearTimeout(enterTimer);$('holdRing').classList.remove('active');if(performance.now()-enterAt>=M.PAUSE_HOLD_MS||role==='pause'){pause();return;}if(role==='serveAim')commenceServe();else if(role==='serve')chooseServe();});
court.addEventListener('pointercancel',()=>clearKeys());court.addEventListener('lostpointercapture',()=>{if(pointerId!==null)clearKeys();});
function startPauseHold(key='pointer'){pauseGestureKey=key;enterAt=performance.now();const started=enterAt;clearTimeout(enterTimer);enterTimer=setTimeout(()=>{if(pauseGestureKey!==key||enterAt!==started||!activeGame()||(key==='pointer'?pointerId===null:!keys[key])||performance.now()-started<M.PAUSE_HOLD_MS)return;enterHeld=true;pause();},M.PAUSE_HOLD_MS);}
document.addEventListener('keydown',e=>{const key=e.code==='NumpadEnter'?'Enter':e.code;if(e.code==='Escape'&&activeGame()){e.preventDefault();pause();return;}if(!['Space','Enter'].includes(key))return;e.preventDefault();if(keys[key]||e.repeat)return;keys[key]=true;
if(choice.active){if(key==='Space'&&choice.brakePress()){braking=true;return;}choice.setInputHeld(true);if(key==='Space'){spaceHeld=false;spaceTimer=setTimeout(()=>{spaceHeld=true;choice.step(-1);spaceRepeat=setInterval(()=>choice.step(-1),sm.getScanInterval());},3000);}else if(view==='serve')startPauseHold(key);return;}
if(view==='serveAim'){if(key==='Enter'||isOneSwitch()){state.serveAimFrozen=true;startPauseHold(key);}else if(!automaticServeAim())state.serveAimDir*=-1;return;}
if(view==='manual'){pointerTarget=null;if(settings.noHold||isOneSwitch())contactIntent=true;if(settings.noHold){tapTarget=M.ballTargetX(state);moveLatched=Number.isFinite(tapTarget);}else if(isOneSwitch()){state.moveDir=oneSwitchDirection();}else{state.moveDir=key==='Space'?-1:1;}moveKey=key;if(key==='Enter'||isOneSwitch())startPauseHold(key);return;}
if(key==='Enter'&&activeGame())startPauseHold(key);
});
document.addEventListener('keyup',e=>{const key=e.code==='NumpadEnter'?'Enter':e.code;if(!['Space','Enter'].includes(key))return;e.preventDefault();if(!keys[key])return;const pauseRelease=pauseGestureKey===key,pauseElapsed=performance.now()-enterAt;keys[key]=false;if(key==='Space'){clearTimeout(spaceTimer);clearInterval(spaceRepeat);if(braking){braking=false;choice.brakeRelease();return;}}if(pauseRelease){clearTimeout(enterTimer);enterTimer=null;pauseGestureKey=null;$('holdRing').classList.remove('active');}
if(pauseRelease&&activeGame()&&pauseElapsed>=M.PAUSE_HOLD_MS){pause();return;}
if(choice.active){choice.setInputHeld(keys.Space||keys.Enter);if(key==='Space'){if(!spaceHeld)choice.step(1);}else choice.select();return;}
if(!enterHeld&&view==='serveAim'&&pauseRelease&&state.serveAimFrozen)commenceServe();if(moveKey===key){moveKey=keys.Space?'Space':keys.Enter?'Enter':null;if(!isOneSwitch()&&moveKey)state.moveDir=moveKey==='Space'?-1:1;}
});

let autoMode=sm.getSettings().autoScan;sm.subscribe(next=>{if(next.autoScan!==autoMode){clearKeys();autoMode=next.autoScan;}updateControls();if(view==='settings')openSettings(returnView,true);});
document.addEventListener('narbe-input-cancelled',lostInput);window.addEventListener('blur',lostInput);document.addEventListener('visibilitychange',()=>{if(document.hidden){checkpoint();lostInput();}});addEventListener('pagehide',checkpoint);document.addEventListener('rally-render-lost',()=>{lostInput();screen('graphics','The court needs a restart.','Your rally is saved. Reload to restore the graphics.',[{id:'reload',title:'Reload game',primary:true,action:()=>location.reload()},{id:'exit',title:'Back to Hub',action:exit}]);});
if(saved&&!validSave(saved))saved=null;
try{scene=new RallyScene($('scene'));home();}catch(error){console.error(error);screen('graphics','The court couldn’t open.','3D graphics are unavailable in this browser.',[{id:'original',title:'Play Lily’s original game',primary:true,action:()=>location.href='../PICKLEBALLRALLY/index.html'},{id:'exit',title:'Back to Hub',action:exit}]);}
function frame(now){const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;const active=activeGame();if(active){
if(view==='serveAim'){state.serveAimCue=state.serveAimFrozen||pointerId!==null?0:automaticServeAim()||keys.Space?state.serveAimDir:-state.serveAimDir;}
if(view==='serveAim'&&pointerId===null&&!state.serveAimFrozen&&(automaticServeAim()||keys.Space)){const bounds=M.serveTargetBounds(state),speed=(automaticServeAim()?.5:.6)*settings.moveSpeed/2.4;state.serveAimX+=state.serveAimDir*speed*dt;if(state.serveAimX>=bounds[1]){state.serveAimX=bounds[1];if(automaticServeAim())state.serveAimDir=-1;}else if(state.serveAimX<=bounds[0]){state.serveAimX=bounds[0];if(automaticServeAim())state.serveAimDir=1;}}
if(view==='manual'&&state.phase!=='serve'){if(Number.isFinite(pointerTarget)){if(M.moveTowardBall(state,dt,settings.moveSpeed*1.6,pointerTarget))pointerTarget=null;}else if(settings.noHold&&moveLatched){if(!Number.isFinite(M.ballTargetX(state))||M.moveTowardBall(state,dt,settings.moveSpeed,tapTarget)){moveLatched=false;tapTarget=null;}}else if(!settings.noHold&&moveKey&&keys[moveKey])M.movePlayer(state,state.moveDir,dt,settings.moveSpeed);}
if(pauseGestureKey!==null&&(keys.Enter||isOneSwitch()&&keys.Space||pointerId!==null)&&activeGame()){const p=M.clamp((now-enterAt-500)/(M.PAUSE_HOLD_MS-500),0,1);$('holdRing').style.setProperty('--hold',p);$('holdRing').classList.toggle('active',p>0);}
// Movement remains live through the bounce; return resolution happens only at contact.
state.scoreFree=noFail();if(contactIntent&&(settings.noHold||isOneSwitch()))M.requestQuickContact(state);
if(view==='flight'||view==='manual')M.update(state,dt*(settings.pace||.55),settings.pace<1,dt);
if(['ready','aim'].includes(state.phase)&&(view==='manual'||view==='flight'))showReady();
if(lastPhase!==state.phaseId){lastPhase=state.phaseId;if(state.phase==='ready'&&(view==='flight'||view==='manual'))showReady();else if(state.phase==='serve')showServe();else if(state.phase==='over')result();}
if(lastEvent!==state.event){lastEvent=state.event;hud();stats.best=Math.max(stats.best,state.best);if(state.lastEvent==='star'){stats.stars++;sound('score');save();}if(state.lastEvent==='return')sound('bank');if(state.lastEvent==='bounce')sound('hover');if(['point','miss','sideout','star','over'].includes(state.lastEvent)){$('feedback').textContent=state.message;feedbackUntil=now+2800;speak(state.message);if(state.lastEvent==='point')sound('score');if(state.lastEvent==='miss')sound('lose');}checkpoint();}
// Finish the return before taking a tap-accessible breather. Keep any target star already earned.
if(noFail()&&state.rally>=6&&state.flight?.direction==='in'&&state.flight.time===0){M.prepareServe(state);state.message='Rally break. '+(state.server===0?'Your serve.':'Robot to serve.')+' Choose Serve or Pause.';showServe();}
if(now-checkpointTime>1000){checkpointTime=now;checkpoint();}}
if(now>feedbackUntil)$('feedback').textContent='';updateDirectionCue();scene?.render(state,active?view:(view==='pause'||view==='settings'&&returnView==='pause'?'paused':'menu'),active?dt:0,settings);requestAnimationFrame(frame);}

requestAnimationFrame(frame);
