/* NARBE Rally Club — deterministic flight, bounce and scoring. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.RallyModel=factory();})(typeof window==='undefined'?globalThis:window,()=>{
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),BALL_RADIUS=.135,BOUNCE_HEIGHT=.195,CONTACT_HEIGHT=1;
const SHOTS={drive:{name:'Drive',duration:1.45,height:1.6,z:-4.65},dink:{name:'Dink',duration:1.55,height:1.45,z:-1.65},lob:{name:'Lob',duration:2.55,height:4.4,z:-5.15}};
// Both robots share one paddle arm: a shoulder socket fixed on the torso and fixed-length
// segments. Extra reach comes only from footwork (a capped lunge), never from the arm.
const ARM={upper:.40,lower:.36,paddle:.72,shoulder:{x:-.38,y:1.44,z:.02},lunge:{x:.8,z:.4}},SERVE_OFFSET=.42,SERVE_DEPTH=-5.7;
// Comfortable contact zones in the robot's stance frame (+z toward the net, -x = paddle side).
const ZONES={fh:{low:{x:[-.74,-.4],z:[.62,.82]},mid:{x:[-.83,-.43],z:[.82,.99]},high:{x:[-.71,-.4],z:[.64,.8]}},bh:{low:{x:[-.14,.45],z:[.65,.805]},mid:{x:[.34,.64],z:[.69,.86]},high:{x:[-.43,.45],z:[.8,.96]}}};
function heightBand(y){return y<.8?'low':y>1.6?'high':'mid';}
function strokeZone(side,y){return ZONES[side<0?'fh':'bh'][heightBand(y)];}
function zoneCenter(side,y){const zone=strokeZone(side,y);return {x:(zone.x[0]+zone.x[1])/2,z:(zone.z[0]+zone.z[1])/2};}
function zoneDepth(y){return (zoneCenter(-1,y).z+zoneCenter(1,y).z)/2;}
// The lunge that brings a stance-frame contact into its zone, and whether that lunge is possible.
function footwork(local,side=local.x<0?-1:1){const zone=strokeZone(side,local.y),x=local.x-clamp(local.x,...zone.x),z=local.z-clamp(local.z,...zone.z);return {x,z,side,reachable:Math.abs(x)<=ARM.lunge.x+1e-9&&Math.abs(z)<=ARM.lunge.z+1e-9};}
function cpuFootwork(s,contact=s.ball,side){return footwork({x:contact.x-s.cpu.x,y:contact.y,z:contact.z-s.cpu.z},side);}
const OPPONENTS=[{name:'FINN-01',description:'A relaxed first rally',speed:1.45,reach:.75},{name:'JULES-02',description:'Quick feet, longer rallies',speed:1.9,reach:.8},{name:'ACE-03',description:'Make every angle count',speed:2.35,reach:.85}];
function create({mode='match',opponent=0,controlMode='manual'}={}){return {mode,opponent,controlMode,rulesVersion:3,server:0,rallyClosed:true,moveDir:1,power:0,pendingShot:null,phase:'serve',phaseId:0,player:{x:0,z:4.6},cpu:{x:0,z:-4.6},ball:{x:.35,y:CONTACT_HEIGHT,z:4.4},flight:null,score:[0,0],rally:0,best:0,stars:0,target:{x:-2.25,z:-4.65},message:'The ball waits for you.',event:0,lastEvent:'ready',shot:'drive',aim:0,aimDir:1,aimFrozen:false,winner:null,pointTimer:0,particles:0,swings:{player:0,cpu:0}};}
function event(s,type,message){s.event++;s.lastEvent=type;s.message=message;}
function phase(s,value){s.phase=value;s.phaseId++;}
function hit(s,aim,shot='drive',assist=true,power){if(s.phase!=='ready'&&s.phase!=='aim')return false;const spec=shotSpec(shot,power);s.rallyClosed=false;s.shot=shot;s.power=Number.isFinite(power)?clamp(power,0,1):.5;const x=assist?clamp(aim,-2.65,2.65):aim;s.rally++;s.best=Math.max(s.best,s.rally);s.playerContact={...s.ball};s.playerStroke=s.ball.y<.8?'low':s.ball.y>1.6?'overhead':s.ball.x<s.player.x?'backhand':'forehand';s.swings.player=.5;s.flight={from:{...s.ball},to:{x,y:BOUNCE_HEIGHT,z:spec.z},contact:{x,y:shot==='lob'?2.25:shot==='dink'?.58:CONTACT_HEIGHT,z:spec.z-.45},cpuSide:x<s.cpu.x?-1:1,bounceAt:.72,bounced:false,time:0,duration:spec.duration,height:spec.height,direction:'out',outside:Math.abs(x)>3.05};clearNet(s.flight);phase(s,'flight');event(s,'hit',spec.name+' to the '+(x<-.85?'left':x>.85?'right':'centre')+'.');return true;}
// Traditional singles side-out scoring: only the server can score.
function point(s,side,reason){if(s.rallyClosed||['point','serve','over'].includes(s.phase))return false;s.rallyClosed=true;s.flight=null;s.pendingShot=null;s.pointTimer=1.4;s.particles=side===0?1:0;
if(s.mode==='rally'||s.scoreFree){s.rally=0;phase(s,'point');event(s,'break','Ready for another serve.');return true;}
let type;if(side===s.server){s.score[side]++;type=side===0?'point':'miss';}else{s.server=side;type='sideout';}phase(s,'point');event(s,type,reason+(type==='sideout'?' Side out. '+(side===0?'Your serve.':'Robot serves.'):(side===0?' Your point.':' Robot’s point.')));if(s.score[side]>=11&&s.score[side]-s.score[1-side]>=2){s.winner=side;phase(s,'over');event(s,'over',side===0?'Match won. Beautifully played!':'Match complete. Let’s go again.');}return true;}
function clearNet(f){const u=-f.from.z/(f.to.z-f.from.z);if(u>0&&u<1){const minimum=(1.08+BALL_RADIUS+.07-(BOUNCE_HEIGHT+(f.from.y-BOUNCE_HEIGHT)*(1-u)))/Math.sin(Math.PI*u);f.height=Math.max(f.height,minimum);}}
function prepareServe(s){s.server=s.server===1?1:0;s.rallyClosed=true;s.pendingShot=null;s.rally=0;s.flight=null;s.aimFrozen=false;const side=s.score[s.server]%2===0?1:-1,spot=servePositions(s);s.player.x=spot.player.x;s.player.z=spot.player.z;s.cpu.x=spot.cpu.x;s.cpu.z=spot.cpu.z;const p=s.server===0?s.player:s.cpu;s.ball={x:p.x+(s.server===0?SERVE_OFFSET:-SERVE_OFFSET),y:.98,z:s.server===0?6.9:-6.9};s.serveAimX=-side*1.55;s.serveAimDir=1;s.serveAiming=false;phase(s,'serve');event(s,'serve-ready',s.server===0?'Your serve. Enter when you are ready.':'Robot to serve. Enter when you are ready.');}
// Where both robots stand for the next serve: the server behind its baseline, on the even/odd side.
function servePositions(s){const server=s.server===1?1:0,side=s.score[server]%2===0?1:-1;return {player:{x:side*1.55,z:server===0?7.6:5.2},cpu:{x:-side*1.55,z:server===1?-7.6:-6.9}};}
// Serves aim anywhere across the legal diagonal box, centre line to sideline, landing deep.
function serveTargetBounds(s){return s.score[s.server]%2===0?[-2.85,-.2]:[.2,2.85];}
function beginServe(s,power=.4,targetX){if(s.phase!=='serve')return false;s.rallyClosed=false;s.power=clamp(power,0,1);s.shot='drive';const side=s.score[s.server]%2===0?1:-1;if(s.server===0){s.ball={x:s.player.x+SERVE_OFFSET,y:.98,z:6.9};s.playerContact={...s.ball};s.playerStroke='low';s.lastHitSide=1;s.flight={from:{...s.ball},to:{x:clamp(Number.isFinite(targetX)?targetX:-side*1.55,...serveTargetBounds(s)),y:BOUNCE_HEIGHT,z:SERVE_DEPTH},contact:{x:clamp(Number.isFinite(targetX)?targetX:-side*1.55,...serveTargetBounds(s)),y:CONTACT_HEIGHT,z:SERVE_DEPTH-.45},bounceAt:.72,bounced:false,time:0,duration:2.4-.5*s.power,height:2.25,direction:'out',isServe:true,outside:false};clearNet(s.flight);s.swings.player=.5;phase(s,'flight');}else{s.ball={x:s.cpu.x-SERVE_OFFSET,y:.98,z:-6.9};s.cpuContact={...s.ball};s.cpuHitSide=-1;s.cpuStroke='low';receiveFlight(s,side*1.55,'serve');s.swings.cpu=.5;}event(s,'serve',s.server===0?'You serve.':'Robot serves.');return true;}
function move(p,to,speed,dt){const dx=to.x-p.x,dz=to.z-p.z,len=Math.hypot(dx,dz);if(len>.001){const m=Math.min(1,speed*dt/len);p.x+=dx*m;p.z+=dz*m;}}
function receiveFlight(s,x,direction='in',contactZ=4.4){s.flight={from:{...s.ball},to:{x,y:BOUNCE_HEIGHT,z:contactZ-1.2},contact:{x,y:direction==='serve'?CONTACT_HEIGHT:[1,.58,1.1,2.05,.65,1.45][s.rally%6],z:contactZ},bounceAt:.66,bounced:false,time:0,duration:direction==='serve'?1.65:1.9,height:direction==='serve'&&s.ball.z>0?.22:1.9,direction,outside:false};phase(s,'flight');}
function serve(s){prepareServe(s);}
function incoming(s){s.cpuContact={...s.ball};s.cpuHitSide=s.ball.x<s.cpu.x?-1:1;s.cpuStroke=s.ball.y<.8?'low':s.ball.y>1.6?'overhead':s.cpuHitSide<0?'forehand':'backhand';const x=clamp(-s.player.x*.45+s.cpu.x*.7+(s.rally%2?1:-1)*1.15,-2.6,2.6);receiveFlight(s,x,'in',[4.9,3.7,2.15,4.9,1.75,3.7][s.rally%6]);s.swings.cpu=.5;event(s,'return','Opponent returns.');}
function sampleFlight(f,t){const b=f.bounceAt;if(t<=b){const u=clamp(t/b,0,1);return {x:f.from.x+(f.to.x-f.from.x)*u,y:BOUNCE_HEIGHT+(f.from.y-BOUNCE_HEIGHT)*(1-u)+Math.sin(u*Math.PI)*f.height,z:f.from.z+(f.to.z-f.from.z)*u};}
const u=clamp((t-b)/(1-b),0,1),rise=u*(2-u);return {x:f.to.x+(f.contact.x-f.to.x)*rise,y:BOUNCE_HEIGHT+(f.contact.y-BOUNCE_HEIGHT)*rise,z:f.to.z+(f.contact.z-f.to.z)*rise};}
function approachRate(f){if(f.direction==='out')return 1;const p=clamp((f.time/f.duration-(f.bounceAt-.16))/.16,0,1);return 1-.68*p*p*(3-2*p);}
function upgradeFlight(s){const f=s.flight;if(f.contact)return;const remaining=Math.max(.7,f.duration-f.time);f.from={...s.ball};f.time=0;f.duration=remaining;f.bounceAt=f.direction==='out'?.72:.66;f.bounced=false;f.contact={x:f.to.x,y:CONTACT_HEIGHT,z:f.direction==='out'?f.to.z-.45:4.4};f.to={x:f.to.x,y:BOUNCE_HEIGHT,z:f.direction==='out'?f.to.z:clamp(s.ball.z+.2,3.2,4.1)};}
function cpuReadyPosition(s,f=s.flight){if(!f?.contact)return {...s.cpu};if(f.cpuSide!==-1&&f.cpuSide!==1)f.cpuSide=f.contact.x<s.cpu.x?-1:1;const centre=zoneCenter(f.cpuSide,f.contact.y);return {x:clamp(f.contact.x-centre.x,-3.2,3.2),z:f.contact.z-centre.z};}
function requestQuickContact(s){const f=s.flight;if(s.phase!=='flight'||!f||f.direction==='out'||Math.abs(f.contact.x-s.player.x)>.7)return false;if(!f.quickRate)f.quickRate=Math.max(1,(f.duration-f.time)/(f.time/f.duration>=f.bounceAt?.22:.5));return true;}
function update(s,dt,slowMotion=true,realDt=dt){dt=clamp(dt,0,.05);realDt=clamp(realDt,0,.05);s.swings.player=Math.max(0,s.swings.player-dt);s.swings.cpu=Math.max(0,s.swings.cpu-dt);s.particles=Math.max(0,s.particles-dt*.5);
if(s.phase==='point'){if(dt>0){const spot=servePositions(s),left=Math.max(dt,s.pointTimer);for(const who of ['player','cpu'])move(s[who],spot[who],Math.max(2,Math.hypot(spot[who].x-s[who].x,spot[who].z-s[who].z)/left),dt);}s.pointTimer-=dt;if(s.pointTimer<=0)prepareServe(s);return;}
if(s.phase==='serve'&&s.server===0){s.ball.x=s.player.x+SERVE_OFFSET;return;}
if(s.phase!=='flight'||!s.flight)return;upgradeFlight(s);const f=s.flight,depth=f.direction==='out'?4.6:f.contact.z+zoneDepth(f.contact.y),depthStep=f.quickRate?Math.max(dt*4.5,Math.abs(depth-s.player.z)*realDt/Math.max(.03,(f.duration-f.time)/f.quickRate)):dt*4.5;s.player.z+=Math.sign(depth-s.player.z)*Math.min(Math.abs(depth-s.player.z),depthStep);f.time+=f.quickRate?realDt*f.quickRate:dt*(slowMotion?approachRate(f):1);const t=clamp(f.time/f.duration,0,1);s.ball=sampleFlight(f,t);if(!f.bounced&&t>=f.bounceAt){f.bounced=true;event(s,'bounce','Bounce.');}
if(f.direction==='out'){if(f.time>.16)move(s.cpu,cpuReadyPosition(s,f),s.mode==='rally'||s.scoreFree?5.5:OPPONENTS[s.opponent].speed,dt);}else{if(s.controlMode==='assisted')move(s.player,{x:f.contact.x-.35,z:f.contact.z+zoneDepth(f.contact.y)},5.5,dt);move(s.cpu,{x:f.direction==='serve'?0:s.cpu.x*.86,z:f.direction==='serve'?-4.6:-3.8},f.direction==='serve'?2.5:.5,dt);}
// A body contact ends the rally instead of letting the ball pass through the robot.
if(f.direction==='out'&&Math.abs(s.ball.x-s.cpu.x)<.46&&Math.abs(s.ball.z-s.cpu.z)<.36&&s.ball.y>.62&&s.ball.y<2.14){point(s,0,'Robot missed the paddle.');return;}
if(t<1)return;
if(f.direction==='out'){
if(!cpuFootwork(s,f.contact).reachable){point(s,0,'Robot could not reach the ball.');return;}
if(s.mode==='rally'||s.scoreFree){incoming(s);return;}
if(f.outside){point(s,1,'Just wide.');return;}const ready=cpuReadyPosition(s,f);if(Math.hypot(s.cpu.x-ready.x,s.cpu.z-ready.z)>OPPONENTS[s.opponent].reach){point(s,0,'Found the open court!');return;}incoming(s);
}else{s.flight=null;if(s.controlMode==='assisted')s.aim=0;s.aimFrozen=false;phase(s,'ready');event(s,'ready',s.rally>1?'Rally of '+s.rally+'. Reach the ball.':'Reach the ball. Your paddle returns it automatically.');}}
const PAUSE_HOLD_MS=6000;
function shotSpec(shot,power){const spec=SHOTS[shot]||SHOTS.drive;if(!Number.isFinite(power))return {...spec};const p=clamp(power,0,1);return {...spec,duration:spec.duration*(1.18-.32*p),height:spec.height*(.8+.4*p),z:shot==='dink'?-1.3-.65*p:shot==='lob'?-4.5-.85*p:-4.2-.8*p};}
function movementBounds(s){return s.phase==='serve'&&s.server===0?(s.score[0]%2===0?[.35,2.7]:[-2.7,-.35]):[-2.7,2.7];}
function movePlayer(s,direction,dt,speed=2.4){const [min,max]=movementBounds(s);s.player.x=clamp(s.player.x+direction*dt*speed,min,max);return s.player.x===min||s.player.x===max;}
function ballTargetX(s){const incoming=s.flight&&s.flight.direction!=='out';if(!incoming&&!['ready','aim'].includes(s.phase))return null;const x=incoming?s.flight.contact.x:s.ball.x,side=x<s.player.x?-1:1;return clamp(x-side*.4,-2.7,2.7);}
function moveTowardBall(s,dt,speed=2.4,target=ballTargetX(s)){if(!Number.isFinite(target))return true;target=clamp(target,-2.7,2.7);const dx=target-s.player.x,step=Math.max(0,dt)*speed;if(Math.abs(dx)<=step){s.player.x=target;return true;}s.moveDir=dx<0?-1:1;s.player.x+=Math.sign(dx)*step;return false;}
function inReach(s){return Math.abs(s.ball.x-s.player.x)<=1.15;}
function autoReturn(s){if(!['ready','aim'].includes(s.phase)||!inReach(s))return false;const offset=s.ball.x-s.player.x,quality=clamp(1-Math.abs(Math.abs(offset)-.4)/.95,0,1),spread=Math.min(2.45,.8+s.rally*.2)*(.65+quality*.35),aim=clamp(-s.cpu.x*.2+Math.sin((s.rally+1)*1.8)*spread+Math.sign(offset)*quality*.2,-2.6,2.6);s.lastHitSide=offset<0?-1:1;s.contactQuality=quality;s.lastPlay=Math.abs(offset)>.85?'dive':s.ball.z<2.6?'close':s.ball.z<4.3?'medium':'deep';s.aim=aim;const hitOkay=hit(s,aim,quality<.4?'lob':'drive',true,.2+quality*.45);if(hitOkay)s.message=quality>.8?'Clean return!':'Ball returned.';return hitOkay;}
function miss(s){if(!['ready','aim'].includes(s.phase)||s.pendingShot)return false;return point(s,1,'Missed the return.');}
function location(x){return x<-2?'Wide left':x<-.85?'Left court':x>.85?(x>2?'Wide right':'Right court'):'Centre court';}
return {create,hit,update,serve,prepareServe,beginServe,servePositions,serveTargetBounds,point,shotSpec,movePlayer,moveTowardBall,ballTargetX,cpuReadyPosition,cpuFootwork,footwork,strokeZone,zoneCenter,zoneDepth,heightBand,ZONES,ARM,SERVE_OFFSET,SERVE_DEPTH,requestQuickContact,movementBounds,inReach,autoReturn,clearNet,miss,PAUSE_HOLD_MS,sampleFlight,approachRate,SHOTS,OPPONENTS,BALL_RADIUS,BOUNCE_HEIGHT,clamp,location};
});
