/* Procedural court and characters. Local Three.js; no remote assets. */
window.RallyScene=function(host){
'use strict';
const T=THREE,scene=new T.Scene();const sky=document.createElement('canvas');sky.width=16;sky.height=512;const skyCtx=sky.getContext('2d'),skyGradient=skyCtx.createLinearGradient(0,0,0,512);skyGradient.addColorStop(0,'#70b7d0');skyGradient.addColorStop(.55,'#c6e4de');skyGradient.addColorStop(1,'#fbefd3');skyCtx.fillStyle=skyGradient;skyCtx.fillRect(0,0,16,512);const skyTex=new T.CanvasTexture(sky);skyTex.colorSpace=T.SRGBColorSpace;scene.background=skyTex;scene.fog=new T.Fog('#cfdfd1',28,85);
const renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.append(renderer.domElement);
const camera=new T.PerspectiveCamera(40,1,.1,120);camera.position.set(11,12,18);camera.lookAt(-2,0,0);
scene.add(new T.HemisphereLight('#e7faff','#647059',1.8));const sun=new T.DirectionalLight('#ffe5b1',3.1);sun.position.set(-10,14,-5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-15,right:15,top:18,bottom:-18,near:1,far:55});sun.shadow.bias=-.0003;sun.shadow.normalBias=.025;scene.add(sun);
const materials={};function mat(color){return materials[color]||(materials[color]=new T.MeshStandardMaterial({color,roughness:.85}));}
function mesh(geo,color,parent=scene){const m=new T.Mesh(geo,mat(color));m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(w,h,d,color,x,y,z,parent=scene){const m=mesh(new T.BoxGeometry(w,h,d),color,parent);m.position.set(x,y,z);return m;}
function sphere(r,color,x,y,z,parent=scene){const m=mesh(new T.SphereGeometry(r,14,10),color,parent);m.position.set(x,y,z);return m;}
function cylinder(r1,r2,h,color,x,y,z,parent=scene,n=12){const m=mesh(new T.CylinderGeometry(r1,r2,h,n),color,parent);m.position.set(x,y,z);return m;}
box(160,.2,160,'#638f75',0,-.5,0);box(11,.25,18,'#d6d0b3',0,-.24,0);box(10.3,.15,17.3,'#356862',0,-.07,0);box(6.12,.03,13.42,'#257d85',0,.02,0);box(6.12,.035,4.26,'#469d96',0,.025,0);
// Fine court aggregate catches the low afternoon light without external textures.
const grain=document.createElement('canvas');grain.width=grain.height=256;const gc=grain.getContext('2d'),pixels=gc.createImageData(256,256);let seed=421;for(let i=0;i<pixels.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;const v=180+(seed%70);pixels.data.set([v,v,v,255],i);}gc.putImageData(pixels,0,0);const grainMap=new T.CanvasTexture(grain);grainMap.wrapS=grainMap.wrapT=T.RepeatWrapping;grainMap.repeat.set(6,13);for(const color of ['#257d85','#469d96','#356862']){mat(color).roughnessMap=grainMap;mat(color).bumpMap=grainMap;mat(color).bumpScale=.012;}
const line='#f4eed5';for(const x of [-3.05,3.05])box(.045,.03,13.42,line,x,.06,0);for(const z of [-6.7,6.7,-2.13,2.13])box(6.15,.03,.045,line,0,.06,z);for(const z of [-4.42,4.42])box(.045,.03,4.54,line,0,.06,z);
// Net mesh is geometry rather than a transparent plane, so the ball stays readable.
for(const x of [-3.6,3.6]){cylinder(.055,.085,1.25,'#ecdfbc',x,.62,0);sphere(.09,'#f9f3d6',x,1.27,0);}box(7.2,.075,.06,'#f4eed5',0,1.06,0);box(7.2,.025,.03,'#244747',0,.18,0);for(let x=-3.5;x<=3.5;x+=.19)box(.014,.88,.014,'#335551',x,.59,0);for(let y=.18;y<1.04;y+=.15)box(7,.012,.012,'#335551',0,y,0);
function sign(text,w,h){const c=document.createElement('canvas');c.width=1024;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle='#103f43';ctx.fillRect(0,0,1024,256);ctx.fillStyle='#d8f78b';ctx.textAlign='center';ctx.textBaseline='middle';let fontSize=92;ctx.font='bold '+fontSize+'px Segoe UI';const usableWidth=c.width-128;if(ctx.measureText(text).width>usableWidth){fontSize=Math.floor(fontSize*usableWidth/ctx.measureText(text).width);ctx.font='bold '+fontSize+'px Segoe UI';}ctx.fillText(text,c.width/2,c.height/2,usableWidth);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tex}));scene.add(m);return m;}
const banner=sign('NARBE RALLY CLUB',7,1.4);banner.position.set(0,2.8,-8.2);box(8,.1,.2,'#e0d1a1',0,3.56,-8.3);for(const x of [-4,4])box(.12,3.5,.12,'#e0d1a1',x,1.75,-8.3);
const baseline=sign('R A L L Y   C L U B',3.8,.95);baseline.rotation.x=-Math.PI/2;baseline.position.set(0,.03,7.6);
const frondMaterial=new T.MeshStandardMaterial({color:'#347957',roughness:.85,side:T.DoubleSide});
function frond(){const vertices=[],indices=[];for(let k=0;k<=12;k++){const t=k/12,w=Math.sin(t*Math.PI)*.28;for(const side of [-1,1])vertices.push(side*w,Math.sin(t*Math.PI)*.42-t*t*.60,t*2.8);}for(let k=0;k<12;k++){const j=k*2;indices.push(j,j+1,j+2,j+1,j+3,j+2);}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(vertices,3));geo.setIndex(indices);geo.computeVertexNormals();return new T.Mesh(geo,frondMaterial);}
for(let i=0;i<10;i++){const x=(i%2?1:-1)*(7+(i%3)*1.7),z=-11+Math.floor(i/2)*5,h=4.5+(i%3)*.4;const trunk=cylinder(.12,.24,h,'#9a8763',x,h/2-.3,z,scene,16);trunk.rotation.z=(i%2?1:-1)*.04;const top=new T.Group();top.position.set(x,h-.4,z);scene.add(top);for(let j=0;j<9;j++){const leaf=frond();leaf.rotation.y=j*Math.PI*2/9;leaf.rotation.x=(j%3)*.12;leaf.castShadow=true;top.add(leaf);}}
// Court-side benches for the robot spectators.
for(const side of [-1,1]){box(.8,.13,4.3,'#d2ad72',side*5.2,.6,-1);box(.1,.5,4.3,'#c19b66',side*5.55,.95,-1);for(const z of [-2.7,.7])box(.6,.6,.12,'#264f4b',side*5.2,.3,z);}
for(const x of [-5,5])for(const z of [-7.5,7.5]){cylinder(.05,.07,4,'#234c47',x,2,z);box(.7,.12,.35,'#e0d9b5',x,4,z);}
// Paddle fronts and robot visors face +Z.
function paddle(parent,color){const g=new T.Group();parent.add(g);const shape=new T.Shape();shape.moveTo(-.13,0);shape.quadraticCurveTo(-.27,.05,-.27,.22);shape.lineTo(-.27,.44);shape.quadraticCurveTo(-.25,.61,0,.62);shape.quadraticCurveTo(.25,.61,.27,.44);shape.lineTo(.27,.22);shape.quadraticCurveTo(.27,.05,.13,0);shape.closePath();const face=mesh(new T.ExtrudeGeometry(shape,{depth:.045,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.016,bevelThickness:.012}),color,g);box(.095,.31,.085,'#183b44',0,-.16,.025,g);for(let i=0;i<7;i++)box(.102,.012,.091,'#527075',0,-.3+i*.045,.025,g);box(.40,.024,.008,'#daef9a',0,.22,.065,g);box(.3,.014,.008,'#daef9a',0,.27,.065,g);return g;}
// Purpose-built court robots: ceramic shells, exposed joints and illuminated visors.
const robotMats={},ledMats={};function alloy(color){return robotMats[color]||(robotMats[color]=new T.MeshStandardMaterial({color,metalness:.42,roughness:.34}));}
function shell(w,h,d,color,x,y,z,parent){const b=Math.min(w,h,d)*.13,r=Math.min(w,h)*.14,X=-w/2+b,Y=-h/2+b,W=w-2*b,H=h-2*b;const p=new T.Shape();p.moveTo(X+r,Y);p.lineTo(X+W-r,Y);p.quadraticCurveTo(X+W,Y,X+W,Y+r);p.lineTo(X+W,Y+H-r);p.quadraticCurveTo(X+W,Y+H,X+W-r,Y+H);p.lineTo(X+r,Y+H);p.quadraticCurveTo(X,Y+H,X,Y+H-r);p.lineTo(X,Y+r);p.quadraticCurveTo(X,Y,X+r,Y);const geo=new T.ExtrudeGeometry(p,{depth:d-2*b,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:b,bevelThickness:b,curveSegments:3});geo.translate(0,0,-d/2+b);const m=mesh(geo,color,parent);m.material=alloy(color);m.position.set(x,y,z);return m;}
function joint(r,x,y,z,parent){const m=sphere(r,'#263e46',x,y,z,parent);m.material=alloy('#263e46');return m;}
function led(w,h,d,color,x,y,z,parent){const m=box(w,h,d,color,x,y,z,parent);m.material=ledMats[color]||(ledMats[color]=new T.MeshBasicMaterial({color}));m.castShadow=false;return m;}
// Both arms share one build: a shoulder socket fixed on the torso, then fixed-length upper-arm and
// forearm groups that are only ever rotated, never scaled. The paddle hand grips the handle.
const ARM=RallyModel.ARM;
function limb(body,color,side){const socket=new T.Vector3(side*Math.abs(ARM.shoulder.x),ARM.shoulder.y,ARM.shoulder.z);joint(.105,socket.x,socket.y,socket.z,body);
const upper=new T.Group();upper.position.copy(socket);body.add(upper);shell(.19,.16,.23,color,0,-.025,0,upper);shell(.13,ARM.upper-.14,.14,color,0,-ARM.upper/2-.01,0,upper);joint(.078,0,-ARM.upper,0,upper);
const fore=new T.Group();body.add(fore);shell(.14,ARM.lower-.06,.15,'#e0e8df',0,-ARM.lower/2,0,fore);led(.023,ARM.lower*.42,.013,'#85f9ed',0,-ARM.lower/2,.078,fore);joint(.07,0,-ARM.lower,0,fore);
const hand=new T.Group();if(side<0){body.add(hand);shell(.15,.14,.14,'#263e46',0,0,0,hand);for(const x of [-.072,.072])box(.035,.13,.09,'#a1b6ba',x,.03,.04,hand);}else{fore.add(hand);hand.position.y=-ARM.lower;shell(.13,.12,.12,'#263e46',0,-.04,0,hand);for(const x of [-.063,.063])box(.035,.12,.08,'#99aeb3',x,-.1,.03,hand);}
return {side,socket,upper,fore,hand};}
function robot(color){const group=new T.Group();group.name='court-robot';scene.add(group);const body=new T.Group();group.add(body);
shell(.49,.57,.34,'#263e46',0,1.16,0,body);shell(.58,.50,.30,'#e2e9dd',0,1.23,.015,body);shell(.37,.30,.065,color,0,1.23,.19,body);for(const x of [-.20,.20])for(const y of [1.06,1.39])joint(.023,x,y,.183,body);shell(.35,.18,.29,'#263e46',0,.81,0,body);for(const x of [-.1,0,.1])box(.04,.08,.02,'#6b8990',x,.81,.157,body);const reactor=mesh(new T.TorusGeometry(.063,.012,6,20),'#85f9ed',body);reactor.material=ledMats['#85f9ed']||(ledMats['#85f9ed']=new T.MeshBasicMaterial({color:'#85f9ed'}));reactor.position.set(0,1.23,.234);box(.29,.37,.10,'#28444c',0,1.2,-.21,body);for(let i=0;i<4;i++)box(.23,.018,.014,'#6b8990',0,1.1+i*.06,-.27,body);
cylinder(.085,.085,.16,'#617a7f',0,1.56,0,body,12);const head=new T.Group();head.name='robot-head';head.position.y=1.84;body.add(head);shell(.62,.44,.43,'#e2e9dd',0,0,0,head);shell(.54,.28,.07,'#132e39',0,-.015,.22,head);const eyes=[];for(const side of [-1,1]){eyes.push(led(.13,.067,.01,'#9bfff1',side*.13,.015,.261,head));const ear=cylinder(.107,.107,.065,color,side*.33,0,0,head);ear.rotation.z=Math.PI/2;led(.035,.065,.015,'#9bfff1',side*.337,0,.075,head);}box(.20,.025,.025,color,0,-.174,.214,head);cylinder(.025,.035,.19,'#546c76',.21,.30,0,head,8);joint(.052,.21,.407,0,head);led(.06,.035,.06,'#9bfff1',.21,.418,0,head);
const legs=[];for(const side of [-1,1]){const leg=new T.Group();leg.position.set(side*.16,.77,0);body.add(leg);joint(.105,0,0,0,leg);shell(.18,.26,.19,color,0,-.19,0,leg);joint(.083,0,-.34,0,leg);shell(.15,.22,.17,'#dce5dd',0,-.49,.015,leg);box(.06,.14,.025,'#66858b',0,-.48,.111,leg);shell(.23,.14,.34,'#263e46',0,-.67,.07,leg);shell(.23,.045,.34,'#a9bac0',0,-.724,.07,leg);legs.push(leg);}
const limbs=[limb(body,color,-1),limb(body,color,1)],bat=paddle(body,'#193a48');bat.name='robot-paddle';bat.scale.setScalar(ARM.paddle);limbs[0].upper.name='robot-upper-arm';limbs[0].fore.name='robot-forearm';limbs[0].hand.name='robot-paddle-hand';return {group,body,head,eyes,legs,limbs,bat,lastX:0,lastZ:0,rig:{}};}
const player=robot('#cef17b'),cpu=robot('#f18e59');player.group.rotation.y=Math.PI;cpu.group.rotation.y=0;cpu.group.name='opponent-robot';
// Small modular spectator bots, with visors and antennae instead of human faces.
const crowd=[];for(const side of [-1,1])for(let i=0;i<3;i++){const g=new T.Group();g.name='spectator-robot';scene.add(g);g.position.set(side*5.18,.1,-2.4+i*1.35);g.rotation.y=-side*Math.PI/2;const color=['#d7ed9b','#f6a579','#a7cadf'][i];shell(.35,.40,.30,color,0,.90,0,g);shell(.42,.31,.30,'#e0e8df',0,1.30,0,g);shell(.34,.15,.025,'#163c48',0,1.30,.161,g);for(const x of [-.08,.08])led(.065,.036,.012,'#9bfff1',x,1.31,.181,g);cylinder(.018,.018,.15,'#617e87',.13,1.52,0,g,6);joint(.035,.13,1.60,0,g);for(const x of [-.24,.24]){joint(.067,x,1.00,0,g);shell(.085,.28,.09,'#879fa3',x,.81,.04,g);}for(const x of [-.11,.11]){shell(.11,.11,.50,'#263e46',x,.66,.24,g);joint(.07,x,.64,.51,g);shell(.10,.35,.11,'#b2c4c4',x,.415,.51,g);shell(.15,.09,.24,'#263e46',x,.195,.58,g);}crowd.push(g);}
// First person uses the same body-mounted arm as the player robot.
player.body.name='player-body';player.head.name='player-head';player.limbs[0].upper.name='player-upper-arm';player.limbs[0].fore.name='player-forearm';player.limbs[0].hand.name='player-paddle-hand';player.bat.name='player-paddle';
const ball=mesh(new T.SphereGeometry(.135,32,24),'#efff5c');ball.position.set(.35,1,4.4);ball.material=new T.MeshStandardMaterial({color:'#efff5c',emissive:'#677e04',emissiveIntensity:.25,roughness:.6});const holeMat=new T.MeshBasicMaterial({color:'#425713'});for(let i=0;i<32;i++){const y=1-2*(i+.5)/32,r=Math.sqrt(1-y*y),a=i*2.399963,n=new T.Vector3(Math.cos(a)*r,y,Math.sin(a)*r);const hole=new T.Mesh(new T.CircleGeometry(.019,14),holeMat);hole.position.copy(n).multiplyScalar(.1354);hole.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),n);ball.add(hole);}
const ballShadow=new T.Mesh(new T.CircleGeometry(.17,20),new T.MeshBasicMaterial({color:'#123e40',transparent:true,opacity:.35,depthWrite:false}));ballShadow.rotation.x=-Math.PI/2;ballShadow.position.y=.09;scene.add(ballShadow);
const aim=new T.Group();scene.add(aim);const target=new T.Mesh(new T.RingGeometry(.3,.38,48),new T.MeshBasicMaterial({color:'#f0ff99',side:T.DoubleSide,transparent:true,opacity:.95}));target.rotation.x=-Math.PI/2;target.position.y=.095;aim.add(target);const dot=new T.Mesh(new T.CircleGeometry(.09,20),new T.MeshBasicMaterial({color:'#fcffd5',side:T.DoubleSide}));dot.rotation.x=-Math.PI/2;dot.position.y=.1;aim.add(dot);const lineGeo=new T.BufferGeometry().setFromPoints(Array.from({length:41},()=>new T.Vector3()));const aimLine=new T.Line(lineGeo,new T.LineDashedMaterial({color:'#dffa9b',dashSize:.12,gapSize:.14,transparent:true,opacity:.7}));scene.add(aimLine);
// Serve aiming: the legal diagonal service box glows; a pin of light over the target reads above the
// net and the receiving robot, and a chevron beside the pin shows which way the target moves.
const serviceBox=new T.Group();scene.add(serviceBox);const boxFill=new T.Mesh(new T.PlaneGeometry(3.05,4.57),new T.MeshBasicMaterial({color:'#e9ff9a',transparent:true,opacity:.24,depthWrite:false}));boxFill.rotation.x=-Math.PI/2;boxFill.position.y=.075;serviceBox.add(boxFill);for(const [w,d,x,z] of [[3.05,.09,0,-2.285],[3.05,.09,0,2.285],[.09,4.57,-1.525,0],[.09,4.57,1.525,0]]){const edge=new T.Mesh(new T.BoxGeometry(w,.014,d),new T.MeshBasicMaterial({color:'#f0ff99'}));edge.position.set(x,.08,z);serviceBox.add(edge);}
const pin=new T.Group();aim.add(pin);const pinHead=new T.Mesh(new T.ConeGeometry(.17,.36,18),new T.MeshBasicMaterial({color:'#f0ff99'}));pinHead.rotation.x=Math.PI;pinHead.position.y=2.6;pin.add(pinHead);const pinBeam=new T.Mesh(new T.CylinderGeometry(.03,.03,2.4,8),new T.MeshBasicMaterial({color:'#f0ff99',transparent:true,opacity:.5,depthWrite:false}));pinBeam.position.y=1.24;pin.add(pinBeam);
const chevron=new T.Mesh(new T.CircleGeometry(.22,3),new T.MeshBasicMaterial({color:'#fcffd5',side:T.DoubleSide}));aim.add(chevron);
const goal=new T.Mesh(new T.RingGeometry(.7,.82,48),new T.MeshBasicMaterial({color:'#ffdb78',side:T.DoubleSide}));goal.rotation.x=-Math.PI/2;goal.position.y=.105;scene.add(goal);
const trail=Array.from({length:10},()=>{const m=new T.Mesh(new T.SphereGeometry(.08,8,6),new T.MeshBasicMaterial({color:'#edffa4',transparent:true,opacity:.3}));scene.add(m);return m;});const history=[];
const confetti=Array.from({length:48},(_,i)=>{const m=mesh(new T.BoxGeometry(.08,.16,.025),['#d8f67a','#f6c280','#f6f7dd'][i%3]);m.visible=false;return m;});

// Fenced palm-court club, layered hills and shaded seating beyond the baseline.
for(const side of [-1,1]){for(let z=-10;z<=10;z+=2){cylinder(.035,.035,2.8,'#517c73',side*6,1.4,z,scene,8);}for(const y of [.25,1.4,2.8])box(.025,.025,20,'#577d71',side*6,y,0);for(let z=-10;z<10;z+=.32)box(.007,2.5,.007,'#76958b',side*6,1.5,z);}
for(let x=-6;x<=6;x+=2)cylinder(.035,.035,2.8,'#517c73',x,1.4,-10,scene,8);for(const y of [.25,1.4,2.8])box(12,.025,.025,'#577d71',0,y,-10);for(let x=-6;x<6;x+=.32)box(.007,2.5,.007,'#76958b',x,1.5,-10);
for(let i=0;i<11;i++){const hill=sphere(1,i%2?'#96b6a1':'#779f91',-40+i*8,-.4,-32-i%3*9);hill.scale.set(9,3+i%4,5);hill.castShadow=false;}
box(7,.22,4,'#f5dfb7',-10,3.25,-13);for(const x of [-13,-7])for(const z of [-14.6,-11.4])box(.13,3.3,.13,'#86775b',x,1.55,z);box(6.2,1.1,1,'#dfc39b',-10,.55,-14);const clubhouse=sign('PALM COURT',4,.65);clubhouse.position.set(-10,2.55,-14.2);
for(const x of [-5.1,5.1]){cylinder(.35,.25,.55,'#eee0bb',x,.275,-6.2);for(let i=0;i<7;i++){const leaf=sphere(.25,'#43785c',x+Math.sin(i*2.4)*.24,.65+(i%3)*.12,-6.2+Math.cos(i*2.4)*.24);leaf.scale.set(.6,1.7,.6);}}
const sunDisc=new T.Mesh(new T.SphereGeometry(2,24,16),new T.MeshBasicMaterial({color:'#fff1c3'}));sunDisc.position.set(-24,21,-58);scene.add(sunDisc);

let elapsed=0,mode='menu',lastEvent=-1,burst=0;function size(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}size();addEventListener('resize',size);
// ---- Strokes ----------------------------------------------------------------------------------
// A stroke runs ready → take-back → contact → follow-through → recovery. Poses are in the robot's
// torso frame (+z faces the net, -x is the paddle side) and stored as arm joints: qu = upper-arm
// frame (its -y runs down the upper arm, its x is the elbow hinge), flex = elbow angle and qw =
// paddle relative to the forearm. The contact key is solved so the paddle face sits one ball
// radius behind the real contact point; take-back and finish turn that same arm at the shoulder,
// so elbow and wrist keep a natural shape. Torso turn, crouch and a capped lunge supply the rest.
const UP=new T.Vector3(0,1,0),DOWN=new T.Vector3(0,-1,0),HINGE=new T.Vector3(1,0,0),SWEET=new T.Vector3(0,.31,.035).multiplyScalar(ARM.paddle),GRIP=new T.Vector3(0,-.17,.025).multiplyScalar(ARM.paddle),GAP=RallyModel.BALL_RADIUS+.04*ARM.paddle,clamp=RallyModel.clamp;
const vec=(x,y,z)=>new T.Vector3(x,y,z),smooth=t=>{t=clamp(t,0,1);return t*t*(3-2*t);},SOCKET=vec(ARM.shoulder.x,ARM.shoulder.y,ARM.shoulder.z);
function basis(x,y){const z=new T.Vector3().crossVectors(x,y);return new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(x,y,z));}
function paddleQuat(axis,normal){const z=normal.clone().addScaledVector(axis,-normal.dot(axis)).normalize();return basis(new T.Vector3().crossVectors(axis,z),axis);}
// Two-bone IK with fixed segment lengths. Elbow flexion stays within 8–150 degrees; out of reach,
// the hand stops short (and the paddle with it) rather than the arm stretching.
const FLEX=[8,150].map(d=>d*Math.PI/180),REACH=[FLEX[1],FLEX[0]].map(f=>Math.sqrt(ARM.upper**2+ARM.lower**2+2*ARM.upper*ARM.lower*Math.cos(f)));
function elbowFor(socket,hand,pole,swivel=0){const d=hand.clone().sub(socket),raw=d.length(),axis=raw>1e-6?d.divideScalar(raw):DOWN.clone(),dist=clamp(raw,REACH[0],REACH[1]),along=(ARM.upper**2-ARM.lower**2+dist*dist)/(2*dist),r=Math.sqrt(Math.max(0,ARM.upper**2-along*along)),bend=pole.clone().addScaledVector(axis,-pole.dot(axis));if(bend.lengthSq()<1e-6)bend.set(0,0,1).addScaledVector(axis,-axis.z);bend.normalize();if(swivel)bend.applyAxisAngle(axis,swivel);
return {elbow:socket.clone().addScaledVector(axis,along).addScaledVector(bend,r),hand:socket.clone().addScaledVector(axis,dist)};}
// Body-space boxes [centre xyz, half size xyz] matching the robot's shells: chest, chest plate,
// reactor, core, backpack, pelvis, neck, thighs and shins. Head boxes (head, visor, ears) are in
// head space and turn with the head.
const BODY_BOXES=[[0,1.23,.015,.29,.25,.15],[0,1.23,.19,.185,.15,.033],[0,1.23,.234,.075,.075,.012],[0,1.16,0,.245,.285,.17],[0,1.2,-.21,.145,.185,.05],[0,.81,0,.175,.09,.145],[0,1.56,0,.085,.08,.085],[-.16,.58,0,.1,.2,.1],[.16,.58,0,.1,.2,.1],[-.16,.2,.07,.12,.2,.17],[.16,.2,.07,.12,.2,.17]],HEAD_BOXES=[[0,0,0,.31,.22,.215],[0,-.015,.22,.27,.14,.035],[-.33,0,0,.033,.107,.107],[.33,0,0,.033,.107,.107]];
function boxGap(p,b){const x=Math.abs(p.x-b[0])-b[3],y=Math.abs(p.y-b[1])-b[4],z=Math.abs(p.z-b[2])-b[5];return Math.hypot(Math.max(x,0),Math.max(y,0),Math.max(z,0))+Math.min(Math.max(x,y,z),0);}
function bodyGap(p,headYaw=0){const h=p.clone();h.y-=1.84;h.applyAxisAngle(UP,-headYaw);return Math.min(...HEAD_BOXES.map(b=>boxGap(h,b)),...BODY_BOXES.map(b=>boxGap(p,b)));}
function armGap(elbow,hand,headYaw){let gap=Infinity;const p=new T.Vector3();for(let i=5;i<=10;i++)gap=Math.min(gap,bodyGap(p.copy(SOCKET).lerp(elbow,i/10),headYaw)-.07);for(let i=0;i<=10;i++)gap=Math.min(gap,bodyGap(p.copy(elbow).lerp(hand,i/10),headYaw)-(i===10?.09:.075));return gap;}
// The elbow follows the stroke's pole; only if that would clip the head or torso does it swivel away.
function solveElbow(hand,pole,headYaw=0,prefer=1){let best=elbowFor(SOCKET,hand,pole);best.gap=armGap(best.elbow,best.hand,headYaw);best.swivel=0;
for(let i=1;i<=9&&best.gap<.015;i++)for(const sign of [prefer,-prefer]){const t=elbowFor(SOCKET,hand,pole,sign*i*.18);t.gap=armGap(t.elbow,t.hand,headYaw);t.swivel=sign;if(t.gap>best.gap+1e-4){best=t;if(t.gap>=.015)break;}}
return best;}
function armFK(j){const u=DOWN.clone().applyQuaternion(j.qu),hinge=HINGE.clone().applyQuaternion(j.qu),qf=new T.Quaternion().setFromAxisAngle(hinge,j.flex).multiply(j.qu),elbow=SOCKET.clone().addScaledVector(u,ARM.upper),hand=elbow.clone().addScaledVector(DOWN.clone().applyQuaternion(qf),ARM.lower);return {elbow,hand,hinge,qu:j.qu,qf,qp:qf.clone().multiply(j.qw)};}
function jointsFrom(elbow,hand,qp){const u=elbow.clone().sub(SOCKET).normalize(),f=hand.clone().sub(elbow).normalize(),flex=u.angleTo(f),hinge=new T.Vector3().crossVectors(u,f).normalize(),qu=basis(hinge,u.clone().negate()),qf=new T.Quaternion().setFromAxisAngle(hinge,flex).multiply(qu);return {qu,flex,qw:qf.invert().multiply(qp)};}
function armIK(b,qp,pole){const hand=GRIP.clone().sub(SWEET).applyQuaternion(qp).add(b),ik=solveElbow(hand,pole);return jointsFrom(ik.elbow,ik.hand,qp);}
// Shoulder turn about the vertical, shoulder lift toward the reach direction, and wrist cock.
function swingJoints(j,turn,lift,cock){const reach=armFK(j).hand.sub(SOCKET);reach.y=0;const side=reach.lengthSq()>1e-6?reach.normalize().cross(UP).normalize():vec(-1,0,0),q=new T.Quaternion().setFromAxisAngle(UP,turn).multiply(new T.Quaternion().setFromAxisAngle(side,lift));return {qu:q.multiply(j.qu),flex:j.flex,qw:new T.Quaternion().setFromAxisAngle(HINGE,cock).multiply(j.qw)};}
// Off hand: hanging, forward for forehand balance, tucked back on backhands.
const HANG=vec(.42,.84,.06),BALANCE=vec(.42,1.0,.26),BRACE=vec(.44,.9,-.08),OFF_POLE=vec(.45,-.25,-1).normalize();
const READY={j:armIK(vec(-.2,1.27,.5),paddleQuat(vec(.42,.9,.17).normalize(),vec(0,0,1)),vec(-.3,-1,-.2).normalize()),yaw:0,lunge:{x:0,z:0},crouch:0,off:HANG};
// Per stroke: paddle elevation across the height band (radians; below zero points the blade down),
// elbow pole and face tilt at contact; torso yaw for [take-back, contact, finish]; shoulder
// turn/lift and wrist cock for take-back and finish; open = extra torso turn per metre the ball
// sits closer to the body than the middle of its zone. A server turns its whole body toward the aim.
const BANDS={low:[.45,.8],mid:[.8,1.6],high:[1.6,2.3]},STROKES={
'fh-mid':{elev:[-.14,1.06],pole:[.1,-1.3,-.05],tilt:.06,yaw:[-.35,.71,.62],prep:[-.5,.1,.01],finish:[.4,.22,-.32],open:[.15]},
'bh-mid':{elev:[-.74,.68],pole:[-.26,-.74,.64],tilt:.06,yaw:[1.22,.9,-.05],prep:[.06,-.43,-.28],finish:[-1.03,.21,-.08],open:[-1.14]},
'fh-low':{elev:[-1.3,-1.15],pole:[-.17,-.6,-.6],tilt:.35,yaw:[-.3,.34,.4],prep:[-.4,0,.2],finish:[.35,.55,0],open:[0]},
'bh-low':{elev:[-.865,-.29],pole:[-.785,-1.005,-.075],tilt:.35,yaw:[.85,.785,.1],prep:[.29,.35,.21],finish:[-.35,.5,.08],open:[-.81]},
'fh-high':{elev:[1.48,1.59],pole:[-1,-.23,.1],tilt:-.2,yaw:[-.58,.21,.35],prep:[-.39,.13,.36],finish:[.09,-.8,-.3],open:[0]},
'bh-high':{elev:[.96,1.35],pole:[-.42,-.54,.12],tilt:-.15,yaw:[1.32,.93,-.07],prep:[-.04,-1.14,.42],finish:[-.59,-.69,.27],open:[-1.14]},
serve:{elev:[-1.4,-.68],pole:[.16,-1.08,-.24],tilt:.3,yaw:[0,.12,-.16],prep:[-.48,.24,.42],finish:[-.47,.34,.34],open:[0]}};
function contactKey(c){const d=STROKES[c.serve?'serve':(c.side<0?'fh':'bh')+'-'+c.band],fw=c.serve?{x:0,z:0}:RallyModel.footwork(c.local,c.side),lunge={x:clamp(fw.x,-ARM.lunge.x,ARM.lunge.x),z:clamp(fw.z,-ARM.lunge.z,ARM.lunge.z)},crouch=c.band==='low'?.12:c.band==='mid'&&!c.serve?clamp((1.1-c.local.y)*.35,0,.08):0,zone=c.serve?null:RallyModel.strokeZone(c.side,c.local.y),turn=zone?-(c.side<0?-1:1)*d.open[0]*(c.local.x-lunge.x-(zone.x[0]+zone.x[1])/2):Math.atan(c.aim||0),yaw=d.yaw[1]+turn,[y0,y1]=BANDS[c.serve?'mid':c.band],e=d.elev[0]+(d.elev[1]-d.elev[0])*clamp((c.local.y-y0)/(y1-y0),0,1);
const n=vec(c.aim||0,d.tilt,1).normalize().applyAxisAngle(UP,-yaw),b=vec(c.local.x-lunge.x,c.local.y+crouch,c.local.z-lunge.z).applyAxisAngle(UP,-yaw).addScaledVector(n,-GAP),axis=vec((c.side<0?-1:1)*Math.cos(e),Math.sin(e),0);axis.addScaledVector(n,-axis.dot(n));
return {d,j:armIK(b,paddleQuat(axis.normalize(),n),vec(...d.pole).normalize()),yaw,turn,lunge,crouch};}
function mix(a,b,t){return {j:{qu:a.j.qu.clone().slerp(b.j.qu,t),flex:a.j.flex+(b.j.flex-a.j.flex)*t,qw:a.j.qw.clone().slerp(b.j.qw,t)},yaw:a.yaw+(b.yaw-a.yaw)*t,lunge:{x:a.lunge.x+(b.lunge.x-a.lunge.x)*t,z:a.lunge.z+(b.lunge.z-a.lunge.z)*t},crouch:a.crouch+(b.crouch-a.crouch)*t,off:a.off.clone().lerp(b.off,t)};}
function strokePose(c){if(c.mode==='idle')return READY;const k=contactKey(c),d=k.d,off=c.side<0?BALANCE:BRACE,key=(j,yaw)=>({j,yaw,lunge:k.lunge,crouch:k.crouch,off}),contact=key(k.j,k.yaw),take=key(swingJoints(k.j,...d.prep),d.yaw[0]+k.turn),finish=key(swingJoints(k.j,...d.finish),d.yaw[2]+k.turn);let p,reach,crouch;
if(c.mode==='follow'){p=mix(mix(contact,finish,1-(1-clamp(c.u/.4,0,1))**2),READY,smooth((c.u-.45)/.55));reach=crouch=1-smooth((c.u-.35)/.55);}
else{p=mix(mix(READY,take,smooth((c.u-.3)/.4)),contact,clamp((c.u-.78)/.22,0,1)**1.6);reach=smooth((c.u-.3)/.35);crouch=smooth((c.u-.5)/.4);}
p.lunge={x:k.lunge.x*reach,z:k.lunge.z*reach};p.crouch=k.crouch*crouch;return p;}
// A change of stroke (new height, rally reset) eases from the pose actually on screen; a change of
// side passes back through the ready paddle in front, so the arm never sweeps through the body.
// Approach and follow-through of the same stroke meet exactly at contact, so they never blend.
function shownPose(a,c,dt){const m=a.rig,key=c.mode==='idle'?'idle':[c.side,c.band,c.serve?1:0].join(':'),target=strokePose(c);
if(m.key!==key){m.from=m.shown||target;m.t=0;m.cross=m.side!==undefined&&c.mode!=='idle'&&m.side!==c.side;m.key=key;}if(c.mode!=='idle')m.side=c.side;m.t+=dt>0?dt:1;
const span=m.cross?.36:.2;m.shown=m.t>=span?target:m.cross?(m.t<span/2?mix(m.from,READY,smooth(m.t/(span/2))):mix(READY,target,smooth(m.t/(span/2)-1))):mix(m.from,target,smooth(m.t/span));return m.shown;}
// Joints → arm, paddle and hand. If the blended arm would touch the head or torso, the elbow
// swivels about the shoulder–hand line; the paddle itself stays exactly where the stroke put it.
function solve(pose,headYaw=0,prefer=1){const fk=armFK(pose.j);fk.gap=armGap(fk.elbow,fk.hand,headYaw);if(fk.gap<.015){const bend=fk.elbow.clone().sub(SOCKET),fix=solveElbow(fk.hand,bend,headYaw,prefer);if(fix.gap>fk.gap){fk.elbow=fix.elbow;fk.gap=fix.gap;fk.swivel=fix.swivel;}}
fk.bat=fk.hand.clone().sub(GRIP.clone().applyQuaternion(fk.qp));return fk;}
function aimLink(group,from,to,hinge){const y=from.clone().sub(to).normalize(),x=hinge.clone().addScaledVector(y,-hinge.dot(y)).normalize();group.quaternion.copy(basis(x,y));}
function applyPose(a,x,z,pose,bob,look,swing){a.group.position.set(x,0,z);a.body.position.y=bob-pose.crouch;a.body.rotation.y=pose.yaw;for(const leg of a.legs){leg.position.y=.77-a.body.position.y;leg.rotation.y=-pose.yaw*.6;}a.head.rotation.y=clamp(look-pose.yaw,-.45,.45);
const arm=solve(pose,a.head.rotation.y,a.rig.swivel||1),limb=a.limbs[0],hinge=new T.Vector3().crossVectors(arm.elbow.clone().sub(SOCKET),arm.hand.clone().sub(arm.elbow));if(hinge.lengthSq()<1e-9)hinge.copy(arm.hinge);if(arm.swivel)a.rig.swivel=arm.swivel;
aimLink(limb.upper,SOCKET,arm.elbow,hinge);limb.fore.position.copy(arm.elbow);aimLink(limb.fore,arm.elbow,arm.hand,hinge);limb.hand.position.copy(arm.hand);limb.hand.quaternion.copy(arm.qp);a.bat.position.copy(arm.bat);a.bat.quaternion.copy(arm.qp);a.rig.arm=arm;
const off=a.limbs[1],ik=elbowFor(off.socket,pose.off.clone().add(vec(0,0,swing)),OFF_POLE),offHinge=new T.Vector3().crossVectors(ik.elbow.clone().sub(off.socket),ik.hand.clone().sub(ik.elbow));if(offHinge.lengthSq()<1e-9)offHinge.set(1,0,0);aimLink(off.upper,off.socket,ik.elbow,offHinge);off.fore.position.copy(ik.elbow);aimLink(off.fore,ik.elbow,ik.hand,offHinge);}
// What a robot's paddle is doing this frame, with the contact in its stance frame.
function serveAim(s,who){const tx=who==='player'?(Number.isFinite(s.serveAimX)?s.serveAimX:0):(s.score[1]%2===0?1:-1)*1.55,tz=who==='player'?RallyModel.SERVE_DEPTH:3.2;return clamp((tx-s.ball.x)/(tz-s.ball.z),-.5,.5);}
function strokeFor(a,s,who){const me=s[who],flip=who==='player'?-1:1,local=p=>({x:(p.x-me.x)*flip,y:p.y,z:(p.z-me.z)*flip}),f=s.flight,swing=s.swings[who],hit=who==='player'?s.playerContact:s.cpuContact,band=RallyModel.heightBand;
if(s.phase==='serve'&&s.server===(who==='player'?0:1))return {mode:'approach',u:1,local:local(s.ball),side:-1,band:'mid',serve:true,aim:serveAim(s,who)};
// The follow-through keeps the contact where it was in the robot's own frame at the hit.
if(swing>0&&hit){if(a.rig.hit!==hit){a.rig.hit=hit;a.rig.hitLocal=local(hit);const ap=a.rig.approach;a.rig.hitSide=ap&&Math.hypot(ap.x-hit.x,ap.z-hit.z)<.35?ap.side:who==='player'?(s.lastHitSide?-s.lastHitSide:0):s.cpuHitSide;}const l=a.rig.hitLocal,serve=who==='player'?!!f?.isServe:f?.direction==='serve',side=serve?-1:a.rig.hitSide||(l.x<0?-1:1);return {mode:'follow',u:1-swing/.5,local:l,side,band:serve?'mid':band(hit.y),serve,aim:serve&&f?clamp((f.to.x-hit.x)/(f.to.z-hit.z),-.5,.5):0};}
if(f?.contact&&(who==='player'?f.direction!=='out':f.direction==='out')){const l=local(f.contact),side=who==='cpu'&&Math.abs(f.cpuSide)===1?f.cpuSide:l.x<0?-1:1;a.rig.approach={x:f.contact.x,z:f.contact.z,side};return {mode:'approach',u:clamp(f.time/f.duration,0,1),local:l,side,band:band(f.contact.y),serve:false};}
if(who==='player'&&['ready','aim'].includes(s.phase)){const l=local(s.ball),side=l.x<0?-1:1;a.rig.approach={x:s.ball.x,z:s.ball.z,side};return {mode:'approach',u:1,local:l,side,band:band(s.ball.y),serve:false};}
return {mode:'idle'};}
// Robots never warp: footwork eases toward its target lunge at a stepping pace, and the body follows
// its court position at no more than a sprint, so even a repositioning reads as movement.
function follow(p,x,z,rate,max,dt){const dx=x-p.x,dz=z-p.z,d=Math.hypot(dx,dz),step=Math.min(rate?d*(1-Math.exp(-dt*rate)):d,max*dt);if(d>1e-9){p.x+=dx/d*step;p.z+=dz/d*step;}}
function animateRobot(a,s,who,dt,reduce,hero){const me=s[who],flip=who==='player'?-1:1,pose=shownPose(a,hero?{mode:'idle'}:strokeFor(a,s,who),dt),m=a.rig,fresh=hero||m.state!==s;m.state=s;
m.lunge??={x:0,z:0};if(fresh){m.lunge.x=pose.lunge.x;m.lunge.z=pose.lunge.z;}else if(dt>0)follow(m.lunge,pose.lunge.x,pose.lunge.z,10,1.5,dt);
const tx=me.x+m.lunge.x*flip,tz=me.z+m.lunge.z*flip;m.at??={x:tx,z:tz};if(fresh){m.at.x=tx;m.at.z=tz;}else if(dt>0)follow(m.at,tx,tz,0,7,dt);
const x=m.at.x,z=m.at.z,moving=Math.hypot(x-a.lastX,z-a.lastZ)>.001;a.lastX=x;a.lastZ=z;
const run=moving&&!reduce?Math.sin(elapsed*16)*.65:0;a.legs[0].rotation.x=run;a.legs[1].rotation.x=-run;const blink=!reduce&&elapsed%4.7>4.56?.16:1;a.eyes.forEach(e=>e.scale.y=blink);
applyPose(a,x,z,pose,who==='player'||reduce?0:Math.abs(run)*.06,who==='cpu'&&!reduce?clamp(Math.atan2(s.ball.x-x,s.ball.z-z),-.5,.5):0,-run*.16);a.group.updateMatrixWorld(true);return pose;}
let lastHero=true,watch=0,serveView=0;
function render(s,view,dt,settings){const reduce=settings.reduceMotion;elapsed+=dt;mode=view;const narrow=innerWidth<700,hero=view==='menu';
animateRobot(player,s,'player',dt,reduce,hero);animateRobot(cpu,s,'cpu',dt,reduce,hero);player.head.visible=hero;
// First person looks out through the player's own visor, so the paddle arm stays rooted at its shoulder.
// The head turns partly toward an incoming ball, keeping low, wide and overhead contacts in view.
if(hero){camera.position.set(11,10,15);camera.fov=40;camera.lookAt(narrow?-1:-3,0,0);}else{const f=s.flight,goal=(f&&f.direction!=='out'?smooth((f.time/f.duration-.45)/.4):['ready','aim'].includes(s.phase)?1:0)*(reduce?.4:.7);watch=lastHero?goal:watch+(goal-watch)*(1-Math.exp(-dt*6));const serveGoal=s.phase==='serve'&&s.server===0?1:0;serveView=lastHero?serveGoal:serveView+(serveGoal-serveView)*(1-Math.exp(-dt*4));
camera.position.copy(player.group.localToWorld(vec(0,1.86+player.body.position.y,.2)));camera.fov=(narrow?85:77)-serveView*(narrow?34:30);const look=vec(camera.position.x,.6,s.player.z-3);look.x+=(s.ball.x-look.x)*watch*.5;look.y+=(s.ball.y-look.y)*watch;look.z+=(s.ball.z-look.z)*watch;
// While serving, the view eases up to frame the far service box; the ball stays at the bottom edge.
if(serveView>.001)look.lerp(vec(camera.position.x+((Number.isFinite(s.serveAimX)?s.serveAimX:camera.position.x)-camera.position.x)*.35,.3,s.player.z-8),serveView);camera.lookAt(look);}lastHero=hero;camera.updateProjectionMatrix();
ball.visible=s.phase!=='point';ball.position.set(s.ball.x,s.ball.y,s.ball.z);if(!reduce&&dt>0&&s.flight&&!settings.freezeBall)ball.rotation.x+=dt*(settings.pace||.55)*6*(settings.pace<1?RallyModel.approachRate(s.flight):1);ballShadow.visible=ball.visible;ballShadow.position.x=s.ball.x;ballShadow.position.z=s.ball.z;ballShadow.scale.setScalar(1+s.ball.y*.14);
const targeting=s.phase==='serve'&&s.server===0&&(view==='manual'||view==='serve'||view==='serveAim');aim.visible=targeting;aimLine.visible=targeting;const spec={z:RallyModel.SERVE_DEPTH,height:2.25};const targetX=s.phase==='serve'?(Number.isFinite(s.serveAimX)?s.serveAimX:-(s.score[s.server]%2===0?1:-1)*1.55):s.aim;target.position.x=dot.position.x=targetX;target.position.z=dot.position.z=spec.z;target.scale.setScalar(reduce?1:1+Math.sin(elapsed*3)*.035);const serveBounds=RallyModel.serveTargetBounds(s);serviceBox.visible=targeting;serviceBox.position.set(Math.sign(serveBounds[0]+serveBounds[1])*1.525,0,-4.415);pin.position.set(targetX,0,spec.z);pin.position.y=reduce?0:Math.sin(elapsed*2.4)*.06;chevron.visible=targeting&&view==='serveAim'&&Math.abs(s.serveAimCue)===1;if(chevron.visible){chevron.position.set(targetX+s.serveAimCue*.5,2.6,spec.z);chevron.rotation.set(0,0,s.serveAimCue>0?0:Math.PI);}
const origin=view==='manual'&&s.flight&&s.flight.direction!=='out'?(s.flight.contact||s.ball):s.ball;const arr=aimLine.geometry.attributes.position.array;for(let i=0;i<=40;i++){const t=i/40;arr.set([origin.x+(targetX-origin.x)*t,(origin.y-RallyModel.BOUNCE_HEIGHT)*(1-t)+RallyModel.BOUNCE_HEIGHT+Math.sin(t*Math.PI)*spec.height,origin.z+(spec.z-origin.z)*t],i*3);}aimLine.geometry.attributes.position.needsUpdate=true;aimLine.geometry.computeBoundingSphere();aimLine.computeLineDistances();goal.visible=false;goal.position.x=s.target.x;goal.position.z=s.target.z;
if(s.phase==='flight'&&dt>0&&!reduce){history.unshift(ball.position.clone());history.length=Math.min(history.length,10);}else history.length=0;trail.forEach((m,i)=>{m.visible=i<history.length;if(m.visible){m.position.copy(history[i]);m.scale.setScalar(1-i/12);m.material.opacity=.26*(1-i/11);}});
if(lastEvent!==s.event){lastEvent=s.event;if(s.lastEvent==='point'||s.lastEvent==='over'||s.lastEvent==='star')burst=1;}burst=Math.max(0,burst-dt*.5);confetti.forEach((m,i)=>{m.visible=burst>0&&!reduce;if(m.visible){const t=1-burst,a=i*2.399;m.position.set(s.player.x+Math.cos(a)*(t*4+.2),1+t*6-t*t*8+(i%5)*.12,s.player.z+Math.sin(a)*(t*3+.2));m.rotation.set(t*7+i,t*5,t*9);}});renderer.render(scene,camera);}
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();document.dispatchEvent(new Event('rally-render-lost'));});const ray=new T.Raycaster(),plane=new T.Plane(new T.Vector3(0,0,1),0),intersection=new T.Vector3();
function aimAt(x,y,z){const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((x-rect.left)/rect.width*2-1,-(y-rect.top)/rect.height*2+1),camera);plane.constant=-z;return ray.ray.intersectPlane(plane,intersection)?intersection.x:null;}
function isBallVisible(point){camera.updateMatrixWorld(true);const p=new T.Vector3(point.x,point.y,point.z),local=p.clone().applyMatrix4(camera.matrixWorldInverse),depth=-local.z;if(depth<=camera.near)return false;const ndc=p.project(camera),ry=RallyModel.BALL_RADIUS/(depth*Math.tan(T.MathUtils.degToRad(camera.fov/2))),rx=ry/camera.aspect;return ndc.z>=-1&&ndc.z<=1&&ndc.x>=-1-rx&&ndc.x<=1+rx&&ndc.y>=-1-ry&&ndc.y<=1+ry;}
// _rig: hook for the Node-only arm checks and stroke tuner in tests/ (no effect on play).
return {render,renderer,aimAt,isBallVisible,_rig:{strokePose,contactKey,strokeFor,solve,armFK,bodyGap,armGap,STROKES,BANDS,READY,SOCKET,BODY_BOXES,HEAD_BOXES,GRIP,SWEET,applyPose,robots:{player,cpu}},dispose(){removeEventListener('resize',size);renderer.dispose();}};

};
