/** End-to-end checks against the real game, never the UI mock. */
module.exports = async function(t) {
  await t.load('apps/games/NARBEKART/index.html');
  await t.until('window.NK && NK.ui && NK.ui.ready', 45000);
  t.assert(await t.js('NK.ui.screen === "title" && getComputedStyle(document.getElementById("loading")).display === "none"'), 'real game boots to title');
  await t.wait(900); await t.shot('01-title');
  await t.js('NK.game.setPick(0,{charId:"pip",vehicleId:"kart"});NK.ui.setScreen("racer",{player:0});true');
  await t.wait(400);await t.shot('02-racer');
  await t.js('NK.debug.start({players:1,type:"single",mode:"nofail",trackId:"meadow"});true');
  await t.wait(600);await t.shot('03-grid');
  await t.until('NK.game.phase() === "racing"', 15000);
  t.assert(await t.js('NK.debug.race().racers.length === 12'), '12-racer grid runs after countdown');
  await t.wait(1000);await t.shot('04-race');
  const x=await t.js('NK.debug.race().humans[0].x');
  await t.press('Space',1000);await t.wait(100);
  t.assert(await t.js('NK.debug.race().humans[0].x')<x-1, 'Space steers the real kart left');
  await t.key('keydown','Enter'); await t.wait(5250);
  t.assert(await t.js('NK.game.isPaused() && NK.ui.screen === "pause"'), 'holding Enter opens pause');
  await t.key('keyup','Enter'); await t.wait(180);
  t.assert(await t.js('NK.ui.__dbg().index === -1'), 'pause swallows the held switch release');
  await t.press('Enter',140); await t.wait(120);
  t.assert(await t.js('NK.game.isPaused() && NK.ui.__dbg().index === 0'), 'first pause press only focuses Continue');
  await t.press('Enter',140);await t.wait(150);
  t.assert(await t.js('!NK.game.isPaused() && !NK.ui.__dbg().overlayOn'), 'Continue resumes the race');
  await t.js('NK.debug.race().humans.forEach(h=>{NK.debug.teleport(h.idx,NK.debug.race().L*3-0.5,0);h.v=25;});true');
  await t.until('NK.ui.screen === "results" && NK.ui.__dbg().overlayOn && !!NK.game.results()',10000);
  t.assert(await t.js('NK.game.results().order.length === 12'), 'race reaches complete results');
  await t.shot('05-results');
  await t.js('NK.debug.start({players:2,type:"single",mode:"open",trackId:"frost"});NK.debug.skipIntro();true');
  await t.wait(700);await t.shot('06-split-side');
  await t.key('keydown','Space');await t.key('keydown','Enter');await t.wait(700);
  t.assert(await t.js('NK.debug.race().humans.every(h=>h.steer === -1)'), 'both split-screen switches steer independently');
  await t.key('keyup','Space'); await t.wait(150);
  t.assert(await t.js('NK.debug.race().humans[0].steer===0 && NK.debug.race().humans[1].steer===-1'), 'releasing P1 does not release P2');
  await t.key('keyup','Enter');
  await t.js('NK.game.settings.set("split","stack");true');await t.wait(250);await t.shot('07-split-stack');
  await t.js('NK.debug.start({players:1,type:"tt",mode:"nofail",trackId:"meadow"});NK.debug.skipIntro();true');
  t.assert(await t.js('NK.debug.race().racers.length===1 && NK.debug.race().humans[0].item==="rocket3"'), 'time trial starts alone with Triple Rocket');
  await t.wait(400);await t.js('NK.debug.teleport(0,NK.debug.race().L*3-0.5,0);NK.debug.race().humans[0].v=25;true');
  await t.until('NK.ui.screen === "results" && NK.ui.__dbg().overlayOn && !!NK.game.results()',10000);
  t.assert(await t.js('!!NK.game.bestTime("meadow","easy") && !!localStorage.getItem("nk-ghost-meadow-easy")'), 'time trial saves best and ghost immediately');
  await t.js('NK.game.startSession();true');
  t.assert(await t.js('NK.debug.stats().ghost'), 'saved time-trial ghost loads on retry');
  t.note('Performance: '+JSON.stringify(await t.js('NK.perf()')));
};
