const {app,BrowserWindow}=require('electron'),fs=require('fs'),path=require('path'),os=require('os');
app.setPath('userData',fs.mkdtempSync(path.join(os.tmpdir(),'ballista-reset-')));
const out=path.join(__dirname,'artifacts'),checks=[],errors=[],wait=ms=>new Promise(r=>setTimeout(r,ms));let w;
const js=s=>w.webContents.executeJavaScript(s);
function assert(ok,name,detail){checks.push({ok,name,detail});if(!ok)throw Error(name+': '+JSON.stringify(detail));}
async function until(s){for(let i=0;i<400;i++){if(await js(s))return;await wait(100);}throw Error('Timeout '+s);}
async function click(label){assert(await js('(()=>{const b=[...document.querySelectorAll("#panelList button")].find(b=>b.querySelector("strong")?.textContent==='+JSON.stringify(label)+');b?.click();return !!b;})()'),'Reach '+label);await wait(120);}
async function fit(name){for(const size of [[1280,900],[640,480],[390,844]]){w.setSize(...size);await wait(200);assert(await js('document.documentElement.scrollHeight<=innerHeight&&[...document.querySelectorAll("#panelTitle,#panelSub,#panelList button")].filter(b=>!b.hidden).every(b=>{const r=b.getBoundingClientRect();return r.top>=0&&r.left>=0&&r.bottom<=innerHeight&&r.right<=innerWidth;})'),name+' fits '+size);fs.writeFileSync(path.join(out,'reset-'+name+'-'+size.join('x')+'.png'),(await w.webContents.capturePage()).toPNG());}w.setSize(1280,900);await wait(200);}
app.whenReady().then(async()=>{w=new BrowserWindow({show:false,width:1280,height:900,webPreferences:{offscreen:true,backgroundThrottling:false}});w.webContents.on('console-message',(_e,l,m)=>{if(l>=3)errors.push(m);});try{
await w.loadFile(path.join(__dirname,'../index.html'));await until('window.RT?.ui&&RT.game.CAM.phase==="MENU"');
await js('(()=>{const G=RT.game,[a,b]=RT.campaigns.kingdoms;for(const k of [a,b]){const id=RT.levels.LEVELS[k.levels[0]].id;G.save.kingdoms[k.id]={next:2,cleared:2,ammo:["boulder","fire"],results:{[id]:{earned:700,shots:1,stars:3}}};G.save.stars[id]=3;}G.save.legacyScore=100;G.save.legacyStars={old:2};G.save.totalScore=1500;G.setAimSounds(true);RT.courses.save({name:"Keep my castle",dist:24,layers:[["K","W"]]});window.other=JSON.stringify(G.save.kingdoms[b.id]);window.castles=JSON.stringify(RT.courses.list());})()');
await click('Play Game');await click('Bramblewick');assert(await js('RT.ui.__test.state().choices.includes("Continue campaign")&&RT.ui.__test.state().choices.includes("Restart progress")'),'Continue and campaign restart are both available');await fit('campaign');
const before=await js('JSON.stringify(RT.game.save)');await click('Restart progress');assert(await js('RT.ui.__test.state().scan===-1&&RT.ui.__test.state().choices[0]==="Cancel"&&!document.querySelector("#panelList .focus")'),'Confirmation opens unselected with Cancel first');await fit('confirmation');
await js('RT.ui.__test.pressReturn();RT.ui.__test.releaseReturn()');assert(await js('RT.ui.__test.state().screen==="resetCampaign"'),'Unselected Enter cannot erase progress');await js('RT.ui.__test.pressSpace();RT.ui.__test.releaseSpace();RT.ui.__test.pressReturn();RT.ui.__test.releaseReturn()');assert(await js('JSON.stringify(RT.game.save)')===before,'Switch Cancel preserves all saved progress');
await click('Restart progress');await js('RT.ui.__test.pressSpace();RT.ui.__test.releaseSpace();RT.ui.__test.pressSpace();RT.ui.__test.releaseSpace();RT.ui.__test.pressReturn();RT.ui.__test.releaseReturn()');
assert(await js('(()=>{const G=RT.game,[a,b]=RT.campaigns.kingdoms;return G.kingdomProgress(a.id).next===0&&G.kingdomProgress(a.id).cleared===0&&G.kingdomScore(a.id).points===0&&a.levels.every(ix=>!G.save.stars[RT.levels.LEVELS[ix].id])&&JSON.stringify(G.save.kingdoms[b.id])===window.other&&G.save.totalScore===800&&G.availableAmmo().map(a=>a.id).join()==="boulder";})()'),'Single reset clears records and ammo only for selected campaign');assert(await js('RT.ui.__test.state().choices[0]==="Start campaign"&&RT.game.currentLevel().order===0&&RT.ui.__test.state().scan===-1'),'Restart returns to first level ready to start');
await w.reload();await until('window.RT?.ui&&RT.game.CAM.phase==="MENU"');assert(await js('RT.game.kingdomProgress("bramblewick").next===0&&RT.game.kingdomProgress("coppercoast").next===2&&RT.game.save.totalScore===800'),'Scoped reset persists across reload');
await click('Settings');await fit('settings');await click('Reset all campaigns');const allBefore=await js('JSON.stringify(RT.game.save)');await click('Cancel');assert(await js('JSON.stringify(RT.game.save)')===allBefore,'Cancel global reset preserves records');await click('Back');await click('Play Game');await click('Coppercoast');await click('Continue campaign');await js('document.getElementById("skipStory").click()');await click('Play level');await js('document.getElementById("ammoSelect").click();document.getElementById("btnPause").click()');await click('Settings');await click('Reset all campaigns');assert(await js('document.getElementById("panelSub").textContent.includes("ends the current game")'),'Gameplay confirmation explains active game ends');await fit('all-confirmation');await click('Cancel');assert(await js('RT.ui.__test.state().screen==="settings"'),'Cancel returns to gameplay settings');await click('Reset all campaigns');await click('Reset all campaigns');
assert(await js('RT.ui.__test.state().screen==="welcome"&&RT.game.CAM.phase==="MENU"&&RT.game.__test.shotCount()===0'),'Global reset ends active run and returns to main menu');assert(await js('Object.keys(RT.game.save.kingdoms).length===0&&Object.keys(RT.game.save.stars).length===0&&RT.game.save.totalScore===0&&!RT.game.save.legacyScore&&!RT.game.save.legacyStars&&RT.campaigns.kingdoms.every(k=>RT.game.kingdomScore(k.id).levels===0&&RT.game.kingdomProgress(k.id).ammo.join()==="boulder")'),'All progress, scores, stars and ammo reset');assert(await js('RT.game.save.aimSounds===true&&RT.courses.list().some(c=>c.level.name==="Keep my castle")'),'Settings and Workshop castles preserved');
await w.reload();await until('window.RT?.ui&&RT.game.CAM.phase==="MENU"');assert(await js('Object.keys(RT.game.save.kingdoms).length===0&&RT.game.save.totalScore===0&&RT.game.save.aimSounds'),'All reset stays cleared after reload');assert(errors.length===0,'No runtime errors',errors);
}catch(e){checks.push({ok:false,name:'Completion',error:e.stack});}finally{fs.writeFileSync(path.join(out,'reset-results.json'),JSON.stringify({checks,errors},null,2));app.quit();}});
