const {app,BrowserWindow}=require('electron');const fs=require('fs'),path=require('path'),os=require('os');
const out=path.join(__dirname,'artifacts');fs.mkdirSync(out,{recursive:true});app.setPath('userData',fs.mkdtempSync(path.join(os.tmpdir(),'ballista-qa-')));let w;const checks=[],errors=[];const wait=ms=>new Promise(r=>setTimeout(r,ms));
function assert(ok,name,detail){checks.push({name,ok,detail});if(!ok)throw Error(name+': '+JSON.stringify(detail));}
async function js(s){return w.webContents.executeJavaScript(s);}
async function until(s,timeout=40000){const at=Date.now();while(Date.now()-at<timeout){if(await js(s))return;await wait(200);}throw Error('Timeout '+s);}
async function click(label){const found=await js('(()=>{const root=document.getElementById(document.getElementById("overlay").hidden?"shotChoices":"panelList");const b=[...root.querySelectorAll("button")].find(b=>b.querySelector("strong")?.textContent==='+JSON.stringify(label)+');if(!b)return false;b.click();return true;})()');assert(found,'Choice reachable: '+label);await wait(330);}
async function key(type,code){await js('document.dispatchEvent(new KeyboardEvent('+JSON.stringify(type)+',{code:'+JSON.stringify(code)+',key:'+JSON.stringify(code==='Space'?' ': 'Enter')+',bubbles:true,cancelable:true}))');}
async function shot(name){await wait(300);fs.writeFileSync(path.join(out,name+'.png'),(await w.webContents.capturePage()).toPNG());}
async function layout(name){const bad=await js('(()=>{const h=document.getElementById("overlay").hidden?document.getElementById("shotChoices"):document.getElementById("panelList");return [...h.querySelectorAll("button")].flatMap(b=>{const r=b.getBoundingClientRect();return r.top<0||r.left<0||r.right>innerWidth+1||r.bottom>innerHeight-30?[{text:b.innerText,rect:[r.x,r.y,r.width,r.height]}]:[];});})()');assert(!bad.length,'Visible choices fit: '+name,bad);const scroll=await js('document.documentElement.scrollHeight<=innerHeight && document.documentElement.scrollWidth<=innerWidth');assert(scroll,'No document scrolling: '+name);}
async function startLevel(){const choices=await js('RT.ui.__test.state().choices');await click(choices.includes('Continue campaign')?'Continue campaign':choices.includes('Start campaign')?'Start campaign':choices.includes('Start level')?'Start level':'Play');if(await js('RT.ui.__test.state().screen==="story"')){await js('document.getElementById("skipStory").click()');await click('Play level');}}
app.whenReady().then(async()=>{w=new BrowserWindow({show:false,width:1440,height:1000,webPreferences:{offscreen:true,backgroundThrottling:false}});w.webContents.on('console-message',(_e,level,message)=>{if(level>=3)errors.push(message);});w.webContents.on('render-process-gone',(_e,d)=>errors.push(d));try{
await w.loadFile(path.join(__dirname,'../index.html'));await until('window.RT?.ui && RT.game.CAM.phase==="MENU"');assert(await js('getComputedStyle(document.getElementById("loading")).display==="none"'),'Game boots to the menu');await shot('01-kingdom-menu');
assert(await js('![...document.querySelectorAll("#panelList button")].some(b=>/More choices|Previous/.test(b.textContent)) && JSON.stringify(RT.ui.__test.state().choices)===JSON.stringify(["Play Game","Settings","How to play","Exit"])'),'Main menu contains exactly Play Game, Settings, How to play, Exit');
await click('Settings');const mainSettings=await js('JSON.stringify(RT.ui.__test.state().choices)');
for(const [width,height]of [[1440,1000],[1024,768],[800,600],[390,844],[640,480]]){w.setSize(width,height);await wait(250);await layout('all settings '+width+'x'+height);await shot('settings-'+width+'x'+height);}
await click('Castle Workshop');assert(await js('RT.ui.__test.state().screen==="editorWarning" && RT.ui.__test.state().choices[0]==="Cancel"'),'Workshop remains behind a cancel-first warning');await click('Cancel');assert(await js('RT.ui.__test.state().screen==="settings"'),'Workshop cancel returns to Settings');await click('Back');await click('Play Game');assert(await js('document.querySelectorAll("#panelList button").length===RT.campaigns.kingdoms.length+2'),'Only kingdoms appear on the campaign menu');await layout('all castles compact');await shot('all-castles-compact');await click('Back');w.setSize(1440,1000);await wait(300);
await click('Play Game');await js('window.qaLibrary=localStorage.getItem("rt-ballista-castles");for(let i=0;i<40;i++)RT.courses.save({name:"Castle "+(i+1)+" · Copperpot Courtyard",dist:24,layers:[["K","W"]]})');await click('My Castles');
for(const [width,height]of [[390,844],[640,480]]){w.setSize(width,height);await wait(250);await layout('full 40 castle library '+width+'x'+height);await shot('full-library-'+width+'x'+height);}await click('Back');await click('Back');await js('if(window.qaLibrary===null)localStorage.removeItem("rt-ballista-castles");else localStorage.setItem("rt-ballista-castles",window.qaLibrary)');w.setSize(1440,1000);await wait(250);
assert(await js('RT.ui.__test.state().scan===-1&&!document.querySelector("#panelList .focus")'),'Welcome begins unselected');await key('keydown','Enter');await wait(320);await key('keyup','Enter');await wait(320);assert(await js('RT.ui.__test.state().screen==="welcome"'),'Unselected Enter does nothing');await key('keydown','Space');await wait(320);await key('keyup','Space');await wait(320);await key('keydown','Enter');assert(await js('RT.ui.__test.state().screen==="welcome"'),'Enter down does not activate');await wait(320);await key('keyup','Enter');await wait(350);assert(await js('RT.ui.__test.state().screen==="levels"'),'Play Game opens kingdom selection');await click('Bramblewick');assert(await js('RT.ui.__test.state().screen==="kingdom" && RT.ui.__test.state().choices.includes("Start campaign")&&!RT.game.__test.narratorState().visible'),'Kingdom has Start, Explore and a narrator scene');await click('Start campaign');await until('!document.getElementById("panelSub").hidden');assert(await js('document.getElementById("panelSub").textContent.length>0 && document.getElementById("caption").textContent.endsWith(document.getElementById("panelSub").textContent)'),'Kingdom story caption matches the current dialogue');await shot('rowan-story');await js('document.getElementById("skipStory").click()');await click('Back');await click('Explore');const exploreBefore=await js('JSON.stringify({save:RT.game.save,blocks:RT.game.__test.blockState()})');const cameraBefore=await js('JSON.stringify(RT.game.__test.camState().camPos)');await js('document.getElementById("exploreNext").click()');await wait(350);assert(await js('JSON.stringify(RT.game.__test.camState().camPos)')!==cameraBefore,'Explore changes camera viewpoint');assert(await js('JSON.stringify({save:RT.game.save,blocks:RT.game.__test.blockState()})')===exploreBefore,'Exploring leaves blocks and progress unchanged');await shot('kingdom-explore');await js('document.getElementById("exploreBack").click()');await wait(350);await startLevel();assert(await js('RT.ui.__test.state().stage==="ammo"'),'Kingdom Play opens ammunition selection');await shot('kingdom-ammo-heading');assert(await js('(()=>{const h=document.querySelector("#ammoPicker>.eyebrow").getBoundingClientRect(),c=document.getElementById("ammoSelect").getBoundingClientRect();return h.bottom<c.top-8;})()'),'Ammo heading stays clear of selected card outline');
assert(await js('document.getElementById("shotbar").hidden && !document.getElementById("ammoPicker").hidden'),'No lower shooting menu');assert(await js('RT.game.availableAmmo().length===1 && RT.game.availableAmmo()[0].id==="boulder"'),'New kingdom starts with Boulder only');await shot('02-side-ammo');
await key('keydown','Space');await wait(320);await key('keyup','Space');await wait(320);await key('keydown','Enter');await wait(320);await key('keyup','Enter');await wait(350);assert(await js('RT.ui.__test.state().stage==="manual"'),'Auto Scan off uses manual aiming');
const yaw0=await js('RT.ui.__test.state().yaw');await key('keydown','Space');await wait(500);const yaw1=await js('RT.ui.__test.state().yaw');await key('keyup','Space');await wait(350);const stopped=await js('RT.ui.__test.state().yaw');await wait(250);assert(yaw1!==yaw0 && await js('RT.ui.__test.state().yaw')===stopped,'Holding Space aims; releasing stops');await key('keydown','Space');await wait(450);await key('keyup','Space');await wait(300);const yaw2=await js('RT.ui.__test.state().yaw');assert((yaw1-yaw0)*(yaw2-stopped)<0,'Each Space press reverses manual aim');await shot('03-manual-world-aim');
await key('keydown','Enter');await wait(350);await js('document.getElementById("btnPause").click()');await wait(350);await key('keyup','Enter');assert(await js('RT.game.boltsUsed===0 && RT.ui.__test.state().screen==="pause" && JSON.stringify(RT.ui.__test.state().choices)===JSON.stringify(["Continue","Change ammunition","Zoom view","Explore level","Settings","How to play","Restart castle","Main Menu"])'),'Pausing during a charge cancels it; key release cannot fire or dismiss pause');await click('Continue');
await key('keydown','Enter');await wait(800);assert(await js('RT.game.boltsUsed===0 && RT.ui.__test.state().charging && RT.ui.__test.state().range>0'),'Enter hold charges without firing');await key('keyup','Enter');await wait(100);assert(await js('RT.game.boltsUsed===1'),'Enter release fires one manually charged shot');await js('document.getElementById("btnPause").click()');await wait(350);const frozen=await js('JSON.stringify(RT.game.__test.shotDebug())');await wait(350);assert(await js('JSON.stringify(RT.game.__test.shotDebug())')===frozen,'Pause freezes flight');await click('Continue');await until('RT.ui.__test.state().stage==="ammo"||RT.ui.__test.state().screen==="results"');if(await js('RT.ui.__test.state().screen==="results"'))await click('Play this castle again');
await js('document.getElementById("ammoSelect").click()');await wait(350);const mouseBefore=await js('RT.game.boltsUsed');const pointerStart=await js('RT.ui.__test.state()');const point=await js('(()=>{const b=RT.game.targetableBlocks().find(b=>b.matId==="L")||RT.game.targetableBlocks()[0],p=RT.game.projectTarget(new THREE.Vector3(b.x,b.y,b.z)),r=document.querySelector("#cvWrap>canvas:not(#minimap)").getBoundingClientRect();return{x:Math.round(r.left+(p.x+1)*r.width/2),y:Math.round(r.top+(1-p.y)*r.height/2)};})()');w.webContents.sendInputEvent({type:'mouseMove',x:point.x-5,y:point.y});await wait(200);w.webContents.sendInputEvent({type:'mouseMove',x:point.x,y:point.y});await wait(300);const hover=await js('RT.ui.__test.state()');assert(hover.yaw!==pointerStart.yaw&&!hover.charging,'Mouse movement aims directly without holding a button');w.webContents.sendInputEvent({type:'mouseDown',button:'left',x:point.x,y:point.y,clickCount:1});await wait(800);const charged=await js('RT.ui.__test.state()');assert(charged.charging&&charged.range>0&&await js('RT.game.boltsUsed')===mouseBefore,'Mouse hold charges without firing');w.webContents.sendInputEvent({type:'mouseUp',button:'left',x:point.x,y:point.y,clickCount:1});await wait(100);assert(await js('RT.game.boltsUsed')===mouseBefore+1,'Mouse release fires exactly one charged shot');await until('RT.ui.__test.state().stage==="ammo"||RT.ui.__test.state().screen==="results"');if(await js('RT.ui.__test.state().screen==="results"'))await click('Play this castle again');
await js('NarbeScanManager.toggleAutoScan()');await js('document.getElementById("ammoSelect").click()');await wait(350);assert(await js('RT.ui.__test.state().stage==="target" && RT.ui.__test.state().targets>0 && RT.ui.__test.state().targets<=5'),'Auto Scan on uses up to five castle target areas');assert(await js('document.getElementById("shotbar").hidden && !document.getElementById("targetLayer").hidden'),'Assisted targets replace menus inside the scene');await shot('04-castle-targets');
for(const [width,height]of [[800,600],[390,844],[640,480]]){w.setSize(width,height);await wait(350);const fit=await js('(()=>{const pins=[...document.querySelectorAll("#targetPins button")].filter(b=>!b.hidden);return pins.every(b=>{const r=b.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight-100;})&&document.getElementById("shotbar").hidden&&document.documentElement.scrollHeight<=innerHeight;})()');assert(fit,'World targets fit without menu or scrolling '+width+'x'+height);await shot('world-targets-'+width+'x'+height);}w.setSize(1440,1000);await wait(350);
await js('NarbeScanManager.toggleAutoScan()');assert(await js('RT.ui.__test.state().stage==="manual"'),'Turning Auto Scan off immediately switches to hold aiming');await js('NarbeScanManager.toggleAutoScan()');assert(await js('RT.ui.__test.state().stage==="target"'),'Turning Auto Scan on restores target-area aiming');
const scan0=await js('RT.ui.__test.state().scan');await wait(2150);assert(await js('RT.ui.__test.state().scan')!==scan0,'One-switch auto scan advances world targets');
await js('document.getElementById("btnChangeAmmo").click()');assert(await js('RT.ui.__test.state().stage==="ammo"'),'Corner action returns to ammo without spending a shot');await js('document.getElementById("ammoSelect").click()');await wait(350);const spent=await js('RT.game.boltsUsed');await key('keydown','Space');await wait(320);await key('keyup','Space');await wait(320);await key('keydown','Enter');await wait(320);assert(await js('RT.game.boltsUsed')===spent,'Assisted fire waits for release');await key('keyup','Enter');await wait(100);assert(await js('RT.game.boltsUsed')===spent+1,'One-switch release fires selected castle target');
await js('document.getElementById("btnPause").click()');await wait(350);await click('Settings');assert(await js('JSON.stringify(RT.ui.__test.state().choices)')===mainSettings,'Gameplay Settings has exactly the same options as main-menu Settings');await shot('06-all-settings');w.setSize(1440,1000);
// Validate import constraints with real game data; malformed files cannot poison saves.
assert(await js('(()=>{try{RT.courses.validate({name:"bad",layers:[["?"]]});return false;}catch{return true;}})()'),'Invalid custom materials rejected');assert(await js('(()=>{try{RT.courses.validate({name:"bad",layers:[["S"]]});return false;}catch{return true;}})()'),'Castles require a crowned target');
const custom=await js('(()=>{const before=JSON.stringify(RT.game.save);const it=RT.courses.save({name:"QA Little Keep",par:1,bolts:4,dist:24,ammo:["stone","boulder"],layers:[["K","W"]]});RT.game.playCustom(it.level);return {id:it.id,before,after:JSON.stringify(RT.game.save),name:RT.game.currentLevel().name};})()');assert(custom.before===custom.after&&custom.name==='QA Little Keep','Custom play does not mutate campaign progress');
// Splitter: one charge, visible mid-flight separation, independent impact targets.
const split=await js(`(()=>{const G=RT.game,A=RT.data.AMMO.find(a=>a.id==='splitter');G.playCustom({name:'Splitter test',dist:24,par:1,bolts:5,layers:[['.......K.......',...Array(7).fill('SWSWSWSWSWSWSWS')]]});const before=G.__test.blockState();const trace=G.fire(A,0,50);const launched=G.__test.shotCount();let frames=0;while(G.__test.shotCount()===1&&frames++<500)G.update(1/120);const children=G.__test.shotDebug();for(let i=0;i<30;i++)G.update(1/120);const separated=G.__test.shotDebug();for(let i=0;i<900;i++)G.update(1/120);const after=G.__test.blockState();return{launched,children,separated,spent:G.boltsUsed,remaining:G.__test.shotCount(),damaged:after.filter((b,i)=>b.hp<before[i].hp).length};})()`);
assert(split.launched===1&&split.children.length===3&&split.children.every(s=>s.fragment),'Splitter opens from one parent into exactly three fragments',split);
assert(new Set(split.separated.map(s=>s.pos[0].toFixed(2))).size===3,'Splitter fragments visibly spread on separate paths',split.separated);
assert(split.children.filter(s=>s.hit==='block').length===3&&split.damaged>=3,'All three fragments independently hit and damage the test wall',split);
assert(split.spent===1&&split.remaining===0,'Splitter spends one shot and resolves every fragment',split);
await w.loadFile(path.join(__dirname,'../editor.html'));await until('window.RT?.editor && RT.editor.__test.blockCount()>0');await shot('07-workshop');assert(await js('!document.getElementById("fatal").classList.contains("on")'),'Editor boots with new models');assert(await js('/stands|stable|pass/i.test(RT.editor.__test.runStability())'),'Editor physics stability',await js('document.getElementById("checkResult").textContent'));
await js('document.getElementById("btnSaveCastle").click()');assert(await js('RT.courses.list().length>=2'),'Editor saves to playable library');assert(await js('document.getElementById("fStory").value===RT.levels.LEVELS[0].story'),'Editor loads individual kingdom story');await js('document.getElementById("btnPrefab").click()');assert(await js('RT.editor.__test.getTool().kind==="paste"'),'Castle prefab arms placement');assert(await js('RT.editor.__test.getClipboard().w===2'),'Tower prefab has real cells');

await js('document.getElementById("btnPalette").click()');await shot('08-block-toybox');
assert(await js('document.getElementById("paletteDialog").open && document.querySelectorAll("#palette>button").length===8'),'Block palette opens with eight paged visual cards');
await js('document.querySelector("[data-tab=prefabs]").click()');await shot('09-structure-toybox');
assert(await js('RT.prefabs.length===18'),'Eighteen built-in structures including rescue prefabs');
assert(await js('(()=>{for(const p of RT.prefabs)RT.editor.placeTemplate({name:p.name,w:p.layers[0][0].length,h:p.layers[0].length,d:p.layers.length,cells:p.layers.map(l=>l.map(r=>r.split("")))});return true;})()'),'Every prefab passes template validation');
await js('document.querySelector("#prefabGrid button").click()');assert(await js('!document.getElementById("paletteDialog").open && RT.editor.tool().kind==="paste"'),'Choosing a prefab closes toybox and arms placement');
assert(await js('(()=>{const E=RT.editor;E.setTool("place","W");const cv=document.querySelector("#stage canvas");cv.dispatchEvent(new WheelEvent("wheel",{deltaY:100,cancelable:true}));const changed=E.tool().matId!=="W";const before=E.tool().matId;cv.dispatchEvent(new WheelEvent("wheel",{deltaY:100,ctrlKey:true,cancelable:true}));return changed&&E.tool().matId===before;})()'),'Wheel cycles blocks; Ctrl-wheel leaves block choice unchanged');
const template=await js('(()=>{const E=RT.editor,T=E.__test;const d=T.gridSnapshot();let a;outer:for(let l=0;l<d.grid.length;l++)for(let r=0;r<d.rows;r++)for(let c=0;c<d.cols;c++)if(d.grid[l][r][c]!=="."){a={layer:l,row:r,col:c};break outer;}T.select(a,a);document.getElementById("btnTemplate").click();document.getElementById("assemblyName").value="QA gatehouse";document.getElementById("btnSaveAssembly").click();const item=E.templates().at(-1);E.importTemplates({items:[item]});E.placeTemplate(item);const before=JSON.stringify(T.gridSnapshot());T.paste(0,0,0);const placed=JSON.stringify(T.gridSnapshot());E.undo();return{saved:item.name,count:E.templates().length,undo:JSON.stringify(T.gridSnapshot())===before,changed:placed!==before};})()');
assert(template.saved==='QA gatehouse'&&template.count===2&&template.changed&&template.undo,'Selection saves, imports, stamps, and undoes without changing original',template);
assert(await js('(()=>{const E=RT.editor,n=E.templates().length;try{E.importTemplates({items:[{name:"Bad",w:1,h:1,d:1,cells:[[["?"]]]}]});return false;}catch{return E.templates().length===n;}})()'),'Malformed template import leaves shelf unchanged');
await js('document.querySelectorAll("dialog[open]").forEach(d=>d.close());document.getElementById("btnPalette").click();document.querySelector("[data-tab=templates]").click()');await shot('10-template-shelf');
for(const [width,height]of [[1024,768],[800,600],[640,480]]){w.setSize(width,height);await wait(200);const fit=await js('(()=>{const d=document.getElementById("paletteDialog");return d.scrollHeight<=d.clientHeight+1&&[...d.querySelectorAll("button")].filter(b=>b.getClientRects().length).every(b=>{const r=b.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth;});})()');assert(fit,'Editor toybox fits without scrolling '+width+'x'+height);}
for(const [width,height]of [[800,600],[640,480]]){w.setSize(width,height);await wait(200);for(const id of ['templateDialog','libraryDialog','rulesDialog','shareDialog']){await js('document.querySelectorAll("dialog[open]").forEach(d=>d.close());document.getElementById('+JSON.stringify(id)+').showModal()');if(id==='rulesDialog'){for(const rule of ['details','story','ammo','structure']){await js('document.querySelector("[data-rule='+rule+']").click()');assert(await js('(()=>{const d=document.getElementById("rulesDialog");return d.scrollHeight<=d.clientHeight+1;})()'),'Editor rules '+rule+' fits '+width+'x'+height);}}else assert(await js('(()=>{const d=document.getElementById('+JSON.stringify(id)+');return d.scrollHeight<=d.clientHeight+1;})()'),'Editor '+id+' fits '+width+'x'+height);}}
assert(!errors.length,'No runtime errors',errors);
}catch(e){checks.push({name:'Completion',ok:false,error:e.stack});try{await shot('failure');}catch{}}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));app.exit(checks.some(check=>!check.ok)||errors.length?1:0);}});
